### ISSUE TITLE
Option to leave out a relay from getting an entity

### ISSUE THREAD

**Issue by Bascht74** [bieniu/ha-shellies-discovery#100]
**Is your feature request related to a problem? Please describe.**

I have a Shelly rgbw2 in "white" mode (white LED stripe) and I am only using the first channel. I don't want the other channels be generated for HA.

**Describe the solution you'd like**

I would like so have an option `disabled` for  `relay-<NUM>`. Right now I can only set `fan`, `light` and so on.
Same thing for a shelly2(.5) where you want to use the 2nd input but you don't need the 2nd output...
In those cases you want to disable that relay but not the device completly.

Seb

**Comment by bieniu** [comment]
You can disable entities you doesn't use in Home Assistant.
