### ISSUE TITLE
RGBW2, power sensor

### ISSUE THREAD

**Issue by dodg3r** [bieniu/ha-shellies-discovery#102]
Hi.

Maybe we can get a power and energy sensor for RGBW2 device?

![image](https://user-images.githubusercontent.com/46417555/101375501-c32ef980-38af-11eb-86b6-facc5673b15d.png)

Thanks

/Jerry

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.35.2

**Comment by bieniu** [comment]
Please fill the template in case of the next issue/feature request.
