### ISSUE TITLE
Adding IP address entity

### ISSUE THREAD

**Issue by thomasgermain** [bieniu/ha-shellies-discovery#104]
**Is your feature request related to a problem? Please describe.**

There is no problem, I just would like to have an entity with the IP address of the shelly.  

**Describe the solution you'd like**

A new entity with IP address.

**Additional context**

The ip address is under `wifi_sta`, so as far as I can understand, it could be added everywhere `rssi` or `ssid` is used (I only have devices with static ip, so maybe the json is not the same if the ip is coming from DHCP ?).

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/105
