### ISSUE TITLE
cannot use entity in node red

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#107]
Hello, 

i installed the plugin, i immediately discovered my shellies, but when i try to use them in node-red i can't find the entities or the domains when using home assistance nodes like call services.

the entity i would like to call for example is "cover.shelly_2_5_office_roller_0" and i want to set roller state to open.

what am i doing wrong?

**Comment by bieniu** [comment]
This is not the right place to ask about node red.
