### ISSUE TITLE
discovery of temperature sensors on Shelly UNI

### ISSUE THREAD

**Issue by JSP80** [bieniu/ha-shellies-discovery#108]
I have two ds18b20 sensors attached to a Shelly UNI. These tempsensors report to the webinterface and to mqtt. But these aren't discovered in HA.

Please add the discovery of temperature sensors to the discovery.
![image](https://user-images.githubusercontent.com/62709893/103527736-17af9f80-4e83-11eb-8f17-23157dceac0c.png)

**Comment by bieniu** [comment]
Is script configuration is valid for external sensors?

**Comment by JSP80** [comment]
Sorry. my mistake. Script config was indeed wrong.
Thank you for the quick reply.
