### ISSUE TITLE
Shelly2.x in Rollermode not supporting all functions

### ISSUE THREAD

**Issue by CubieMedia** [bieniu/ha-shellies-discovery#109]
**Describe the bug**

Using Shelly2.x in Roller Mode it does not show the current (live) state of the roller.

This does not happen since the state_topic is not used in roller_mode also the state send from shelly does not fit to the configuration from the shellies-discovery script and the CoverEntity Code from Home Assistant.

Does anyone else experience this?

**Expected behavior**

When closing/opening the Cover the state of the entity in homeassistant should change. It also should show in the GUI with a blue arrow which direction the Cover goes.

This behaviour is needed for a toggle function i currently try to implement for Home Assistant
https://github.com/home-assistant/core/pull/45789

The easiest thing would be to make shelly transmit different states.
open -> opening
close -> closing
stop -> current state of the cover (open/close)

like it is defined in your script

**Versions:**
 - Home Assistant: 2021.1.5
 - Shellies Discovery: 37.0
 - Shelly device firmware: 1.9.4 (also tested with 1.9.0, 1.8, 1.7)

**Comment by bieniu** [comment]
How can I improve this? We can use `position_topic` or `state_topic`, so I think there is currently no solution to your issue.

![image](https://user-images.githubusercontent.com/478555/106729951-55345380-660e-11eb-87ce-bf8ae7141a23.png)

> The easiest thing would be to make shelly transmit different states.

I'm not a Shelly firmware developer.

**Comment by CubieMedia** [comment]
You stand correct!

My question is which side to adjust ... Home Assistant or Shelly.
What would you prefer?

**Comment by bieniu** [comment]
I'm not 100% sure, but I think MQTT Cover would need to listen to `position_topic` and `state_topic` simultaneously and set `state_opening` or `state_closing` as the entity state based on `state_topic`.

> Also would you add state_topic to roller mode?

Currently, `position_topic` is a better solution.

**Comment by CubieMedia** [comment]
After https://github.com/home-assistant/core/pull/43949 is solved it is possible to use both topics.

After my PR (see description) it will show live state again.

**Comment by bieniu** [comment]
Great! I'll update the script after merging this PR.

**Comment by bieniu** [comment]
You can test the new cover using the script from `enhance-cover` branch https://github.com/bieniu/ha-shellies-discovery/tree/enhance-cover

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/112
