### ISSUE TITLE
Shelly i3 shortpush flooding my history

### ISSUE THREAD

**Issue by artkrz** [bieniu/ha-shellies-discovery#110]
**Describe the bug**

My history is flooded with i3 short-push messages when I'm not even using it.

**Expected behaviour**

Show entries when short-push is really triggered.

**Versions:**

 - Home Assistant: 2021.2.0
 - Shellies Discovery: 0.37.0
 - Shelly device firmware: 20201124-092930/v1.9.0@57ac4ad8

**Shellies Discovery automation:**

Not sure what should I provide here. Sorry.

**Debug log:**

No log but history is full off:

![obraz](https://user-images.githubusercontent.com/209375/106817021-93655d80-6676-11eb-8c07-c6f35c9ee82d.png)

**Comment by bieniu** [comment]
Take a look here https://github.com/bieniu/ha-shellies-discovery/issues/91

The problem has been reported to Shelly, I don't know when it will be fixed

![image](https://user-images.githubusercontent.com/478555/106859030-c8979d00-66c2-11eb-9761-6f01330be9ce.png)

**Comment by artkrz** [comment]
Thanks.
