### ISSUE TITLE
Add support to Shelly motion sensor

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#111]
Shelly just released the Shelly motion sensor. Please add support for it. 
I already ordered it and once it arrives I can help testing the integration.

**Comment by bieniu** [comment]
Please read the documentation
![Screenshot_20210213-002355__01](https://user-images.githubusercontent.com/478555/107832925-fdc28000-6d91-11eb-8a27-acdddbad7041.jpg)
