### ISSUE TITLE
Shelly Duo white temperature

### ISSUE THREAD

**Issue by pbzdyl** [bieniu/ha-shellies-discovery#115]
Hi,

First of all thank you for this great project!

I'm just starting with Home Assistant so I might be missing something. My Shelly Duo was correctly discovered and added as a device and it seems it doesn't include white temperature controls/sensor.

I guess the `color_temp_*` configuration of the [`light.mqtt`](https://www.home-assistant.io/integrations/light.mqtt/#color_temp_command_template) integration would need to be added.

Would it be possible to add support for this?

**Comment by pbzdyl** [comment]
Oh, I've just checked the dashboard card for the light control for this device and it does support changing the color temperature so I guess it's managed automatically by the `light.mqtt` integration by detecting `color_temp` value from the MQTT messages. I'm still not sure if there should be a separate sensor added by `ha-shellies-discovery` for `color_temp` value?

**Comment by bieniu** [comment]
> I'm still not sure if there should be a separate sensor added by `ha-shellies-discovery` for `color_temp` value?

What for?

**Comment by bieniu** [comment]
I'm closing due to no response.
