### ISSUE TITLE
'No ACK from MQTT server in 10 seconds' errors

### ISSUE THREAD

**Issue by pbzdyl** [bieniu/ha-shellies-discovery#116]
With the latest version (ed366e0feaf209086de10bc597037ec782a50c63) from master branch I am getting a lot of the following error messages in the logs:

```
No ACK from MQTT server in 10 seconds
```

It results in many of the entities to be unavailable in HA.

https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.38.1 change log explicitly mentions a fix for this issue and I can confirm that specific revision works, but there must have been some change after that release that broke this again.

**Comment by bieniu** [comment]
This issue is related to Mosquitto Addon 5.1.1 https://github.com/home-assistant/addons/issues/1887
