### ISSUE TITLE
Invalid time stamp in device view

### ISSUE THREAD

**Issue by dylan09** [bieniu/ha-shellies-discovery#117]
**Describe the bug**
For discovered Shellies in configuration device view Device Uptime shows "Invalid timestamp".

**Expected behavior**
Display of timestamp

I am using macOS Big Sur and Safari. Maybe it is related to time stamp formatting. If I could remember me right, it must be in ISO 8601 format. Under templating there is a warning regarding this.
 
**Versions:**
 - Home Assistant: 2021.2.3 
 - Shellies Discovery: 0.37.0
 - Shelly device firmware: 

Added a snapshot from configuration -> device.
<img width="317" alt="Bildschirmfoto 2021-03-17 um 10 10 19" src="https://user-images.githubusercontent.com/13660768/111457218-38646300-8718-11eb-8a6f-96ece168863c.png">

**Comment by bieniu** [comment]
Please show me this `uptime` sensor state in **Developers Tools** >> **States**.

**Comment by dylan09** [comment]
Developer tools state show valid time stamp: 
```
2021-03-17 09:20:27
```

**Comment by bieniu** [comment]
So state of the sensor is correct. I can't do anything about this, this is frontend issue.

**Comment by dylan09** [comment]
Hello,

want to give additional feedback. Seems macOS Safari is a little bit petty regarding time stamp.
If I open the shelly device in device view it displays "Invalid Time Stamp".

Opening the page in FireFox (on macOS or Windows) it displays the correct time stamp. E.g. it displays "1 day" if the shelly was startet yesterday.

Actually I could not test it with LoveLace.
Do you know where the time stamp is created/formatted? Maybe I could test with the date time format options.
