### ISSUE TITLE
Option to suppress Shelly Type prefix on discovery

### ISSUE THREAD

**Issue by dylan09** [bieniu/ha-shellies-discovery#118]
When the script discover a new device it will prefix the typename with the type of the shelly (Shelly 1, Shelly 1L) ...

In the script you use 
```
device_name = f"{model} {dev_id.split('-')[-1]}"
```
to create the device_name.

I would like to have the devices in HA named according to the mqtt topic I named the shelly in his web gui. So I would like to have an option to disable the model prefix.
Currently I patch the code to get rid of the model name prefix.

Thanks
Ulrich

**Comment by bieniu** [comment]
Do you use something like this?
`device_name = "dev_id.split('-')[-1]"`

**Comment by bieniu** [comment]
You can change device name in the UI

![image](https://user-images.githubusercontent.com/478555/111458449-b83efd00-8719-11eb-80a8-d44ec49f58ef.png)

**Comment by dylan09** [comment]
I have changed the python code 'brute force' 😀 Delete every occurrence of ```{model} ``` where the devicename was build.

Yes. I know I could change it in the UI. But the device name is not the main problem. Its also used for entity_name in entities of that device. And that clutters all my entity names. Entity names follow a scheme which starts with a code for room and type of device. So I could see and order them after room and code.
And I use a lot of yaml and node-red. There I also would use the names I gave them as MQTT topic in the Shelly Web UI.

Maybe there are other outside who don't like to have the type in front of the name. 
Every time I delete a device from HA I have to rename the device/entities so that existing yaml (homekit, customize, ...) and node-red is working.

It is not of high priority. Because delete/re-add of devices is not an every day task.

**Comment by bieniu** [comment]
I opened some time ago this feature request on Allterco Gitlab server:

![image](https://user-images.githubusercontent.com/478555/111467865-3b198500-8725-11eb-8485-0bf2a0d872a1.png)

If they add `device name` and `channel name` to the `announce` topic the script will use this names.

For now you can use `relay-<NUM>-name`, `light-<NUM>-name` and `roller-<NUM>-name` parameters:
```yaml
shellyswitch-123409FF:
        relay-0: "fan"
        relay-0-name: "Bathroom Fan"
        relay-1: "light"
        relay-1-name: "Livingroom Light"
```

**Comment by dylan09** [comment]
I know I could change the device name via automation.yaml. But I would like to have the MQTT device name as entity_name in HA.
For example I set the custom mqtt prefix in Shelly Web UI to ```RM_YY_Description```it is announced with this name to MQTT broker. You use this prefix to apply changes in behaviour (switch -> light, switch -> cover, ...) in automations.yaml. But when creating the device (and the responding enties) you add the model in front of the prefix.

**Comment by bieniu** [comment]
Close via https://github.com/bieniu/ha-shellies-discovery/commit/3c2a12c77606233322ea5c02b8a480551bfe040e

**Comment by dylan09** [comment]
Thank you. Great job.
