### ISSUE TITLE
Wrong energy value from Shelly Plug S

### ISSUE THREAD

**Issue by nu00** [bieniu/ha-shellies-discovery#12]
Hi, i've a problem with the energy value from my shelly plug s. It shows 1.0kWh instead of 10W. 
![Schermata del 2020-01-08 18-24-54](https://user-images.githubusercontent.com/59661437/72000845-775d7580-3244-11ea-9df0-d2eb2a03981d.png)
![Schermata del 2020-01-08 18-25-03](https://user-images.githubusercontent.com/59661437/72000846-775d7580-3244-11ea-970b-6444f096bb4a.png)

**Comment by bieniu** [comment]
Unit of power is W and unit of energy is kWh. Why do you compare two different sensors?

**Comment by nu00** [comment]
Because i'm stupid, sorry.
