### ISSUE TITLE
More states for Shelly 2.5 in roller mode

### ISSUE THREAD

**Issue by Asafb26** [bieniu/ha-shellies-discovery#120]
Reopening #84 to see if we have a new way to get the "opening" and "closing" states.

currently, I'm using the current power state of the module (greater than 0) to simulate a binary sensor of a "moving" state, can we integrate it?

**Comment by bieniu** [comment]
Cover entities use `state` and `position` topic now https://github.com/bieniu/ha-shellies-discovery/commit/de046eb448c0a7be60ee685f6ca08dc0b3bfbe41

**Comment by Asafb26** [comment]
Probably in missing something here, what is `stat_closing` anyway and `stat_opening`? How do you measure this state? AKAIK shelly not provide this data, right?

**Comment by bieniu** [comment]
Device provide this data

![Screenshot_20210328-174440](https://user-images.githubusercontent.com/478555/112758221-69cd1080-8fed-11eb-89c3-04c3ae752658.jpg)


Look here https://github.com/bieniu/ha-shellies-discovery/issues/109

**Comment by Asafb26** [comment]
that's awesome! missed it somehow, im closing this issue, thanks
