### ISSUE TITLE
Shelly UNI changed input reporting

### ISSUE THREAD

**Issue by gigatexel** [bieniu/ha-shellies-discovery#123]
**Describe the bug**

Shelly Uni no longer reports input status on `shellies/shellyuni-<id>/input/<i>`

**Expected behavior**

According to the Shelly API website:

`shellies/shellyuni-<deviceid>/input_event/<i> for each SW input <i>; reports input event and event counter, e.g.: {"event":"S","event_cnt":2} see /status for details
`

**Versions:**
 - Home Assistant: all
 - Shellies Discovery: latest
 - Shelly device firmware: 10.1

**Comment by bieniu** [comment]
Is this a change from firmware 1.10?
According to the documentation, the device should still send the subject `input`.

![image](https://user-images.githubusercontent.com/478555/113303151-13b7e000-9301-11eb-9955-695448301ba1.png)

**Comment by gigatexel** [comment]
I see, you are right.

I updated to 10.1 and `/input<i>` is now permanently 0
Will downgrade now to test.

**Comment by gigatexel** [comment]
Deactivated mqtt on Shelly UNI and reactivated. Works again :-)
