### ISSUE TITLE
Shelly EM output relay broken

### ISSUE THREAD

**Issue by gigatexel** [bieniu/ha-shellies-discovery#125]
**Describe the bug**

Since one or two updates ago, the Shelly EM relay is no longer working with the script.
The current status is not reported and it cannot be controlled.

**Expected behavior**

**Versions:**
 - Home Assistant: 2021.4.1
 - Shellies Discovery: latest
 - Shelly device firmware: latest

**Comment by bieniu** [comment]
Please post debug log for `python_script` component.

**Comment by gigatexel** [comment]
Logs: https://www.dropbox.com/s/ewvkdjb80pd4m8a/logs.txt?dl=0

Shelly EM device is shellies/shellyem-airco

**Comment by bieniu** [comment]
There is no `shellyem-airco` in this log. There is `shellyem-inductie` in the log but its configuration is correct.

BTW, look here https://github.com/home-assistant/addons/issues/1887

**Comment by gigatexel** [comment]
Reinstalled MQTT Add-On and all MQTT warnings are gone now.

But shellyem-airco cannot be found anymore now. I removed the device, rebooted HA, but does not reappear.
Can I debug or force this by any means?

Shelly EM is online and MQTT config ok (was not changed on device).
Also rebooted the Shelly.

**Comment by bieniu** [comment]
You can use MQTT-Explorer to check that you see MQTT topics from this device on MQTT broker.

**Comment by gigatexel** [comment]
I installed the now deprecated mqtt-addon as a broker. Works fine now.
