### ISSUE TITLE
Inform user in log when MQTT prefix chosen in firmware is too long

### ISSUE THREAD

**Issue by maichai** [bieniu/ha-shellies-discovery#126]
**Describe the bug**

Shelly 1PM not recognized as online, although it is visible in MQTT

Root cause:
If the topic name of the device is longer than 32 chracters, it will shorten some topics where the value is long
shortened topics: (normal topic > example shortened topic)

online > onl
announce > ann
info > inf

**Expected behavior**

 
if it is detected, that the topics are shortened, the user should be informed in the log file with a concise message saying they should chose an MQTT prefix shorter than 32 characters

**Versions:**
 - Home Assistant: 2021.4.6
 - Shellies Discovery: 0.39.3
 - Shelly device firmware: 20210415-131256/v1.10.3-g23074d0

**Shellies Discovery automation:**

```yaml

```

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
The shortening takes place if the name (`custom_very_long_name`) or the entire topic (`shellies/custom_very_long_name`) is longer than 32 characters?

**Comment by maichai** [comment]
this is not really a bug in the addon, it is more of a quirk of the shellys, but the addon shoudl help the user to find the problem.

my first assumption was that the shortening happens, if custom_very_long_name>32, I have not deeply investigated it, but it happened at around that amount of characters for custom_very_long_name

I know that you advocate not to use a custom topic, but if you adhere to some rules it works quite nicely.

**Comment by bieniu** [comment]
OK, I'll ask Shelly dev team about this.

**Comment by bieniu** [comment]
Shelly team will fix this in the future version of the firmware and I'll add a custom prefix length check to the script.

**Comment by maichai** [comment]
awesome

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/commit/dfe1374795bd944914a3d6f349737d31bdc95bdc
