### ISSUE TITLE
ShellyEM duplicated entity

### ISSUE THREAD

**Issue by fsteccanella** [bieniu/ha-shellies-discovery#13]
Hi, 
after a restart the energy meter "0" is duplicated inside the entity registry.
During startup i can find:
```
Component has already been discovered: sensor shellyem-B9F090-power-0, sending update
Component has already been discovered: sensor shellyem-B9F090-energy-0, sending update

Registered new sensor.mqtt entity: sensor.shellyem_b9f090_power_0_2
Registered new sensor.mqtt entity: sensor.shellyem_b9f090_energy_0_2
```

To fix i have to manually adjust the entity_id on the device page:

![image](https://user-images.githubusercontent.com/5019896/72362223-0d851600-36f3-11ea-8f95-55a68af3fc4a.png)
![image](https://user-images.githubusercontent.com/5019896/72362249-1970d800-36f3-11ea-8243-7ca5b5b42693.png)

Deleting the duplicated "_0" entities and renaming back the "_0_2" one to "_0"

Can you help me?
Thanks

**Comment by bieniu** [comment]
I don't know what causes this issue. It happens sometimes after Shelly firmware update. To fix that  you have to re-add MQTT integration or manually edit entity registry (not recommended).

**Comment by fsteccanella** [comment]
It's does not happens only after a firmware update, but also after a simple hass restart (not always anyhow).

**Comment by bieniu** [comment]
After first HA restart AFTER firmware upgrade. I had similar situation with another component so I'm not sure that this is my script issue.

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/commit/20a557650c0f659ccabc0217f9ee46df3fc2aa41
