### ISSUE TITLE
Last_reset and state_class attributes

### ISSUE THREAD

**Issue by gigatexel** [bieniu/ha-shellies-discovery#135]
The new Energy window in HA provides insight in energy usage and integrates with individual power meters (like Shelly Devices).
However, for these measurements to be integrated in the Energy window, the energy measurements need the last_reset and state_class attributes set.
this is not the case for the energy-related entities based on the Shelly MQTT-script.

**Comment by bieniu** [comment]
Work in progress, You can test this by installing script from the `master` branch.

**Comment by bieniu** [comment]
Close via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.40.1

**Comment by gigatexel** [comment]
I think it is not het implemented for the totals counter in shelly EM (shellies/shellyem-<deviceid>/emeter/<i>/total)

**Comment by Random-Cow** [comment]
Looks like the total counter are missing `state_class: measurement`
For example this are the attributes for energy0 for my Shelly3EM:
`state_class: measurement
last_reset: '1970-01-01T00:00:00'
unit_of_measurement: kWh
friendly_name: 3EM Meter Energy 0
device_class: energy`

and this for total power0:
`last_reset: '1970-01-01T00:00:00'
unit_of_measurement: kWh
friendly_name: 3EM Meter Total 0
device_class: energy`

**Comment by bieniu** [comment]
> on second thought isn't last_reset for the energy entities wrong?

What do you mean?

**Comment by bieniu** [comment]
> Looks like the total counter are missing `state_class: measurement`

https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.40.2

**Comment by Random-Cow** [comment]
> https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.40.2

Thanks for the quick implementation 👌.

>> on second thought isn't last_reset for the energy entities wrong?

>What do you mean?

This is how all graphs for the energy entites of my 3EM look like in home-assistant
![grafik](https://user-images.githubusercontent.com/33932801/128604992-44c46889-225f-4fc4-b4d1-bb5f15ea1ff7.png)

This is how the total entities look like in comparison:
![grafik](https://user-images.githubusercontent.com/33932801/128605163-01c1c66e-e5e1-49c8-8001-c71866db0a20.png)

As far as i can see in the offical documentation (and how my shelly plug s behaves) the energy entities should also increase over time.

I also recorded the energy values directly in mqtt:
![grafik](https://user-images.githubusercontent.com/33932801/128606015-49e40c45-9f91-48ef-9c5b-2d1a59f84592.png)



I hope you can understand what i mean. But it looks to me it's more of a problem with my 3EM, i will try a factory reset and see if that makes any difference, if not i will try and contact the shelly support.
