### ISSUE TITLE
Shelly need update but no newer firmware exist 

### ISSUE THREAD

**Issue by pixiandreas** [bieniu/ha-shellies-discovery#139]
Got this in the Home-assistant log.
ValueError: Firmware dated 20210720 is required, please update your device shellyrgbw2-AF9511

Latest firmware for this is 20210429-101353/v1.10.4-g3f94cd7 
http://api.shelly.cloud/files/firmware

**Versions:**
 - Home Assistant: 2021.8.6
 - Shellies Discovery: 0.40.2

**Comment by dylan09** [comment]
Same problem here. Couldn't update to last version of script. No Update available for my SHRGBW2.
Has somebody information, when to expect an update for SHRGBW2? Shelly support isn't very responsive at the moment.

**Comment by bieniu** [comment]
You can try 1.11.4-rc firmware http://repo.shelly.cloud/firmware/rc/
