### ISSUE TITLE
Long_Push entity binary sensor falls back to false

### ISSUE THREAD

**Issue by boevink** [bieniu/ha-shellies-discovery#140]
Not sure if this is related to the script, but I have a Shelly Dimmer 2 configured and working via MQTT.
For the following topics however the status of the entity in HA seems not to be reflected correctly:
shellies/shellydimmer2-XXX/longpush/0
shellies/shellydimmer2-XXX/longpush/1

Within MQTT Explorer the value of these topics show the latest action, meaning '1' for a long-push and '0' for a short-push.
As soon as a longpush is set to '1' in the MQTT topic, this is correctly reflected in the HA binary sensor entity, however while the MQTT topic stays at '1' (after releasing the switch), the HA entity sensor falls back to '0'/false after a second.

**Comment by bieniu** [comment]
This behavior is by design. `shortpush` and `longpush` are events that take a while, so the sensor state is `on` when an event occurs (to trigger the automation) and then returns to `off` after a while.
