### ISSUE TITLE
Shelly EM / 3EM - provide a consumption sensor for the sum of all phases to provide to utility_meter

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#148]
**Is your feature request related to a problem? Please describe.**
This is a feature request to allow simpler integration with utility_meter 

**Describe the solution you'd like**

provide something similar to the below as an additional entity provided by the script/integration

```
- platform: template
  sensors:
    total_power_consumption_kwh:
      friendly_name: "Total Power Consumption"
      unique_id: sensor.total_power_consumption_kwh
      unit_of_measurement: "kWh"
      icon_template: "mdi:flash"
      value_template: >
        {% if states('sensor.shelly_3em_meter_total_0') == "unavailable" or
              states('sensor.shelly_3em_meter_total_1') == "unavailable" or
              states('sensor.shelly_3em_meter_total_2') == "unavailable" %}
          unavailable
        {% else %}
          {{ ((states('sensor.shelly_3em_meter_total_0') | float) + 
              (states('sensor.shelly_3em_meter_total_1') | float) + 
              (states('sensor.shelly_3em_meter_total_2') | float)) | round(2)
          }}
        {% endif %}
```
The above doesn't see to be sufficient because the value provided can return "0" instead of unavailable after HA reboots.
as can be seen here

![image](https://user-images.githubusercontent.com/4518931/133060826-327177e0-e38d-4fe5-90bf-6c52acc42d59.png)

**Additional context**

Utility_meter integration needs a sensor that provides the sum of all phases to calculate a consumption properly

**Comment by bieniu** [comment]
Sorry, the script creates entities only for values provided by the device. You have to ask about this feature Shelly team.
