### ISSUE TITLE
UTF8 in discovery topic

### ISSUE THREAD

**Issue by flic** [bieniu/ha-shellies-discovery#150]
MQTT topics can include UTF8 characters, but as it turns out Home Assistant discovery topics cannot.

I was wondering why some of my devices didn't turn up in HA, and found this in the HA log:

2021-09-14 11:39:35 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/binary_sensor/tvättstuga/tvättmaskin-flood/config'

I don't much fancy renaming a lot of devices and related MQTT-based automations. Would it be possible (and not too much work) for your script to convert the discovery topic to something HA-approved? I'd most certainly appreciate it.

Thanks.

**Comment by bieniu** [comment]
Show me please payload of this config topic.

**Comment by flic** [comment]
This is the discovery topic:

homeassistant/binary_sensor/tvättstuga/tvättmaskin-flood/config

...and this is the payload:

`{"name": "Shelly Flood tvättstuga/tvättmaskin Flood", "stat_t": "~sensor/flood", "en": "True", "uniq_id": "tvättstuga/tvättmaskin-flood", "qos": 0, "dev": {"ids": ["84cca8b149d6"], "name": "Shelly Flood tvättstuga/tvättmaskin", "mdl": "Shelly Flood", "sw": "20210909-144708/v1.11.4-DNSfix-ge6b2f6d", "mf": "Allterco Robotics"}, "~": "shellies/tvättstuga/tvättmaskin/", "pl_on": "true", "pl_off": "false", "exp_aft": 51839, "dev_cla": "moisture"}`

**Comment by bieniu** [comment]
Please test this version https://github.com/bieniu/ha-shellies-discovery/blob/utf8/python_scripts/shellies_discovery.py

**Comment by flic** [comment]
Seems to be working. It justs removes åäö from the topics, and the devices are created in Home Assistant. The device names are correct in HA and the devices work, no errors that I can find.

Thanks!

**Comment by bieniu** [comment]
Great! Thanks for testing.
