### ISSUE TITLE
Add support to the plus and pro line 

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#154]
Please add support to Shelly Pro and Plus lines.
The existing mqtt topics changed and the script isn't able to operate them correctly. I own a plus, I'm happy to help

**Comment by bieniu** [comment]
First release of Shellies Discovery Gen2 is available here https://github.com/bieniu/ha-shellies-discovery-gen2

**Comment by anubisg1** [comment]
NICE!! thank you!!
