### ISSUE TITLE
Shelly UNI ADC voltage missing precision 

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#160]
The ADC voltage sensor seems to be rounded at the first decimal value.
This is loosing critical precision that the UNI provides instead.

The sensor in HA shows 0.1, but the UNI reports 0.12 instead.

In some applications like water tank levels, a 0.01 increase it's meaningful

**Comment by anubisg1** [comment]
Hello,

Even if https://github.com/bieniu/ha-shellies-discovery/commit/75eb5048f5159b55960fcc19055dbfe2eeefa2f8  was committed and released, the sensor still provides 1 decimal place of accuracy.

A manually created mqtt sensor reading shelloes/<name>/adc/0  without manipulation returns the correct expected value

I'm currently running 0.41.0

**Comment by bieniu** [comment]
Show me please debug lug for python_script integration.

**Comment by anubisg1** [comment]
it got fixed after a second reload of HA core for some reason.

thank you!
