### ISSUE TITLE
Device-url links to "none"

### ISSUE THREAD

**Issue by gigatexel** [bieniu/ha-shellies-discovery#162]
**Describe the bug**

When consulting the device's page on the MQTT integration, the device's webpage links to `none`
Happens to all my devices (plug, plugs, EM, 2.5)
**Expected behavior**

**Versions:**
 - Home Assistant: 2021.11.0
 - Shellies Discovery: latest
 - Shelly device firmware: multiple versions

![image](https://user-images.githubusercontent.com/65073191/140756304-2be3bfe6-0319-44dd-9180-ce9674cda06c.png)

**Comment by oramirite** [comment]
Hi, I'd just like to ask, is this what the purpose of the configuration change in `shellies_discovery` is? There isn't really an adequate explanation for what purpose it serves and it's not associated with an actual ticket.

**Comment by bieniu** [comment]
The script needs an IP address of the device to add correct "Visit device" link. The script configuration should be changed before update.
