### ISSUE TITLE
Gen2 - differentiate between Stable and Beta firmware upgrades

### ISSUE THREAD

**Issue by TheGroundZero** [bieniu/ha-shellies-discovery#163]
**Is your feature request related to a problem? Please describe.**

`binary_sensor.shellyplus...firmware_update` almost always reports `Update available` as there's very often a Bèta upgrade available.
I have a 'System Monitoring' dashboard which displays all entities with entity_id `binary_sensor.shelly*_firmware_update`.
The Shelly Plus is always visible, even though there's no Stable firmware upgrade available.

**Describe the solution you'd like**

Differentiatie between Stable and Beta firmware upgrade.
I.e. have seperate sensors for both.

**Additional context**

![image](https://user-images.githubusercontent.com/2406013/140936410-8d33e362-3291-4f78-83c5-b7212fdd956c.png)

**Comment by TheGroundZero** [comment]
Ignore this.

This script doesn't integrate Gen2 devices.
Sensor is provided by built-in integration.

**Comment by bieniu** [comment]
First release of Shellies Discovery Gen2 is available here https://github.com/bieniu/ha-shellies-discovery-gen2
