### ISSUE TITLE
Adding Shelly Plus 1

### ISSUE THREAD

**Issue by AdilMalle** [bieniu/ha-shellies-discovery#164]
Hi, 
can you please add the new Shelly plus 1 in the devices list?
Thank you

**Comment by bieniu** [comment]
This script will not support plus/pro devices. When I will have time I write a new one for these devices.

**Comment by lexnared** [comment]
Hi.
Do you have new information?

**Comment by bieniu** [comment]
I'm currently refactoring the gen1 script. When I'm done I will start working on the gen2 script.

**Comment by lexnared** [comment]
Thanks for your feedback.
Until then, I will connect the Shelly Plus 1 via MQTT.

**Comment by bieniu** [comment]
First release of Shellies Discovery Gen2 is available here https://github.com/bieniu/ha-shellies-discovery-gen2
