### ISSUE TITLE
Add device ip information

### ISSUE THREAD

**Issue by akanegally** [bieniu/ha-shellies-discovery#165]
Hello, your project works really great but I have a suggestion to make it even better!

Since the last release (novembre 2021), it's possible to visit the device's web interface(if it has one).
Check https://www.home-assistant.io/blog/2021/11/03/release-202111/#visit-devices-and-services.

This feature is particularly usefull for shelly devices since they all have a web interface.

When I want to configure a shelly device, I need to remember the ip address which is not ideal.

What do you think ? Is it something complex to do ?

I take benefit from this opportinuty to thank you for all the work you accomplished

**Comment by bieniu** [comment]
Please read the changelog.
