### ISSUE TITLE
Shelly pro 4 PM Wanted 

### ISSUE THREAD

**Issue by fabiannmb** [bieniu/ha-shellies-discovery#166]
Can you add support for shelly pro 4 PM and the other new shelly devices?

**Comment by bieniu** [comment]
This script will not support gen 2 devices. I plan to create a new script but I don't know when I'll have time for it.

**Comment by bieniu** [comment]
First release of Shellies Discovery Gen2 is available here https://github.com/bieniu/ha-shellies-discovery-gen2
