### ISSUE TITLE
Firmware status / update?

### ISSUE THREAD

**Issue by jdeluyck** [bieniu/ha-shellies-discovery#17]
Hi,

I was wondering if there's some way to expose the new_fw flag, and perhaps a switch to trigger an update to the shelly?

```
"new_fw": true
```
in the announce message

**Comment by bieniu** [comment]
Does device send `announce` topic with `"new_fw": true` when it detects new firmware available? Or it waits to restart or command `announce`?

**Comment by jdeluyck** [comment]
It looks like it only does it on announce or start - that I can see

**Comment by bieniu** [comment]
So I think there isn't point in creating a sensor that will not automatically receive data from the device to update its state.

**Comment by jdeluyck** [comment]
I don't entirely agree. You could easily call /announce a few times a day (or once a day) to get an idea. The problem is that right now you have absolutely no idea what the status is.

**Comment by bieniu** [comment]
Yo can use rest sesnors for update available info https://github.com/bieniu/home-assistant-config/blob/master/sensors.yaml#L64-L89

**Comment by jdeluyck** [comment]
Finally had a look at this. Unfortunately my shellies are on an entire network alltogether, with no direct access (MQTT is being proxied). I've had a look if I couldn't use the output from shellies/announce together with an mqtt sensor, but sofar no luck.

**Comment by bieniu** [comment]
Closed via: https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.25.4
