### ISSUE TITLE
Duplicated devices after updating to 2020.12

### ISSUE THREAD

**Issue by jonferreira** [bieniu/ha-shellies-discovery#183]
**Describe the bug**
After updating to the latest script version + HA 2020.12 (which introduces the new button entity) new entities for each shelly were created using the new button entity. Unfortunately these new entities have created new devices instead of using the already existing devices.

![Screenshot 2021-12-19 120913](https://user-images.githubusercontent.com/7714292/146674384-2690088d-a4bc-4757-8e82-c349eb5de505.png)

**Expected behavior**
New entities should use the already existing devices

**Versions:**
 - Home Assistant: 2020.12.3
 - Shellies Discovery: latest, updated today
 - Shelly device firmware: latest, updated today

**Comment by bieniu** [comment]
My bad, already fixed.

**Comment by bieniu** [comment]
After a few HA restarts, the old devices will have no entities and you need to remove them.

**Comment by jonferreira** [comment]
Cool thanks. 

Anything I need to do other than updating the script and restart?

**Comment by bieniu** [comment]
Nope.

**Comment by jonferreira** [comment]
I've updated the py script and restart a couple of times but so far don't see any difference. I still have every shelly duplicated with the majority of entities on the "new devices", i.e. devices created yesterday and with the "wrong name", where as the "old devices", i.e. devices that already existed, have the right name and allocated to the right areas, are left with only a handful of entities

**Comment by jonferreira** [comment]
@bieniu unsure if it's related but just noticed all my Shellie's "cu" property are showing as "none" as well

![Screenshot 2021-12-20 124908](https://user-images.githubusercontent.com/7714292/146769625-ba83d0bd-6e16-4bca-bf4c-3da1d5f6b8f7.png)

Looking at the code this is set with 

``KEY_CONFIGURATION_URL: f"http://{host}/"`` 

so seems for some reason the script isn't getting "host" right?

**Comment by jonferreira** [comment]
OK so I've been comparing differences between latest script version and the one I had before and think I've figured it out.

Previously you had the config payload with:

``
KEY_DEVICE: {
                **KEY_IDENTIFIERS: [mac],**
                KEY_NAME: device_name,
                KEY_MODEL: model,
                KEY_SW_VERSION: fw_ver,
                KEY_MANUFACTURER: ATTR_MANUFACTURER,
            }
``

where as now it's:

``
KEY_DEVICE: {
            KEY_CONNECTIONS: [[KEY_MAC, format_mac(mac)]],
            KEY_NAME: device_name,
            KEY_MODEL: model,
            KEY_SW_VERSION: fw_ver,
            KEY_MANUFACTURER: ATTR_MANUFACTURER,
            KEY_CONFIGURATION_URL: f"http://{host}/",
        }
``

So now I have each device duplicated, one - already existing - device with the ID and with at least one entity, usually the "controller" one(s) and one - new - device, without the ID,  with the remaining entities.

Any suggestions on what should I do to untangle this big mess? I presume edit the script and add the KEY_IDENTIFIERS: [mac] would "fix it" for now but would also stop me from updating. I also assume you had a good reason for this change so don't want to mess with things I don't fully understand.

**Comment by bieniu** [comment]
Did you restart HA? In my case, after two or three restarts, the "old" devices were without entities and I removed it.

**Comment by jonferreira** [comment]
Yes I did restart a couple of times.

The devices do have entities. The Dimmer 2 devices for example, the "controller", i.e. the light entity that turns on / off / dim the lights, are still being created on the "old device", all the other sensors are on the "new device".

Looking at the code it seems the Dimmer 2 is still being hardcoded to add the id - https://github.com/bieniu/ha-shellies-discovery/blob/master/python_scripts/shellies_discovery.py#L4335

In all honestly I'd rather have all the entities on the "old devices", else I have dozens of devices to rename and allocate again.

**Comment by bieniu** [comment]
> Looking at the code it seems the Dimmer 2 is still being hardcoded to add the id

Ops I didn't catch this.

> Is there a specific reason why KEY_IDENTIFIERS: [mac] was removed though?

It is recommended to use `connections` instead of `identifiers` because then it is possible to use one device entry for several integrations.

**Comment by jonferreira** [comment]
>>>>Ops I didn't catch this.
Dimmer 2 is not only one, if I read it correctly bulbs are the same

>>>>It is recommended to use connections instead of identifiers because then it is possible to use one device entry for several integrations.
Makes sense.

Any suggestions on how I can get my system back to normal then?

**Comment by bieniu** [comment]
> Dimmer 2 is not only one, if I read it correctly bulbs are the same

Yes, that's weird, I'm pretty sure I've already changed that 🤔

> Any suggestions on how I can get my system back to normal then?

You have to wait for my fix. I'll try to prepare it today.

**Comment by jonferreira** [comment]
OK thanks.

As a quick fix I've manually edit the script to remove the ``ids`` part, restart HA and now the "old dimmer 2 devices" were left without entities and the "new dimmer 2 devices" have all the entities. Great, I suppose.

So guess I'll have no other option other than to to manually removed all the "old devices", rename and re-alocate to areas all the "new devices"?

Also, all my Shelly 1/2.5 "old devices" were left with an orphan "xxx_temperarure_status" entity - think this was a typo and needs to be manually removed?

**Comment by bieniu** [comment]
> So guess I'll have no other option other than to to manually removed all the "old devices", rename and re-alocate to areas all the "new devices"?

You can remove old device via Configuration -> Integrations -> MQTT -> device -> Remove and yes, you need to re-alocate new devices.

**Comment by jonferreira** [comment]
OK will wait for your final fix and will do that, PITA since it's a lot of devices.

Thanks for the effort.

**Comment by bieniu** [comment]
The idea of migration was:
- add `connections`
- wait few weeks (few versions)
- remove `identifiers`.

But I messed up unfortunately.

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/commit/5c7af0cacacf9b904da18e605f3571d5048fb8e8
