### ISSUE TITLE
Support for the new Pro and Plus devices

### ISSUE THREAD

**Issue by tkreeftmeijer** [bieniu/ha-shellies-discovery#184]
It would be great if the relative new Shelly Pro and Plus devices could be added to the script.

I tried to look at the script, but I don't have enough knowledge to add them to the script.

Are there plans to support those new devices?

**Comment by bieniu** [comment]
Duplicate https://github.com/bieniu/ha-shellies-discovery/issues/166

**Comment by bieniu** [comment]
First release of Shellies Discovery Gen2 is available here https://github.com/bieniu/ha-shellies-discovery-gen2
