### ISSUE TITLE
Error executing script

### ISSUE THREAD

**Issue by DanNielsen** [bieniu/ha-shellies-discovery#224]
LOG:
Logger: homeassistant.components.python_script.shellies_discovery.py
Source: components/python_script/__init__.py:222
Integration: Python Scripts (documentation, issues)
First occurred: 07.23.36 (25 occurrences)
Last logged: 07.36.10

Error executing script: host value None is not valid, update shallies_discovery automation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 912, in <module>
ValueError: host value None is not valid, update shallies_discovery automation

**Comment by bieniu** [comment]
Please read this error once again `update shallies_discovery automation`.

**Comment by DanNielsen** [comment]
> Please read this error once again `update shallies_discovery automation`.

I have newest update? How to update again?

**Comment by bieniu** [comment]
You have to update the automation, not the script.
