### ISSUE TITLE
Shelly Door/Window 2 --> Lux sensor subscribed to wrong topic

### ISSUE THREAD

**Issue by cginebrosa** [bieniu/ha-shellies-discovery#225]
**Describe the bug**

In a SDW2 device, the lux sensor is always showing as unavailable.
After looking at shellies_discovery.py, I've found that lux sensor is subscribed to wrong topic "shellies/shellydw2-XXXXX/status" instead of "shellies/shellydw2-XXXXXX/sensor/lux"

**Expected behavior**

Changed code to subscribe to "shellies/shellydw2-XXXXXX/sensor/lux".
See attached file "shellies_discovery_MOD_CGP001.py" and look for comment "# MOD_CGP001" to see changes

**Versions:**
 - Home Assistant: 2021.12.5
 - Shellies Discovery: 0.43.2
 - Shelly device firmware: 20211109-125737/v1.11.7-g682a0db

**Shellies Discovery automation:**

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
 

**Debug log:**

No error showed on debug log. Just subscribed to wrong topic

[shellies_discovery_MOD_CGP001.py.txt](https://github.com/bieniu/ha-shellies-discovery/files/7821388/shellies_discovery_MOD_CGP001.py.txt)

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/227
