### ISSUE TITLE
Shelly 2.5 Power 0 and Energy 0 not available

### ISSUE THREAD

**Issue by focusyzfr6** [bieniu/ha-shellies-discovery#226]
**Describe the bug**
  After the device has been taught in, the entities Power 0 and Energy 0 are displayed but are never available.

**Expected behavior**

**Versions:**
 - Home Assistant: 2021.12.3
 - Shellies Discovery: 0.43.2
 - Shelly device firmware: 20211109-125214/v1.11.7-g682a0db

**Shellies Discovery automation:**

```yaml

```

**Debug log:**
No error showed on debug log

```txt

```

**Comment by bieniu** [comment]
And where is the debug log?

**Comment by focusyzfr6** [comment]
Hey, i am new in here. Can you tell me where i can find it or how I can
generate it?

Am Do., 6. Jan. 2022 um 14:52 Uhr schrieb Maciej Bieniek <
***@***.***>:

**Comment by bieniu** [comment]
https://github.com/bieniu/ha-shellies-discovery#how-to-debug

**Comment by focusyzfr6** [comment]
Sorry i didn't see this. Now i get logs (testet it with by manually run the script and got the 'payload_json'  error. But I can't see any other errors.

**Comment by focusyzfr6** [comment]
after several "Shellies Announce" and restarts of HS the power and energy entities worked. Unfortunately all energy and power entities from all shellys got renamed.
