### ISSUE TITLE
Issue with with Shelly 2.5 roller shutter sensor_shelly_2_5_*_{power,energy}{,_0,_1} after recent changes

### ISSUE THREAD

**Issue by LarsMichelsen** [bieniu/ha-shellies-discovery#230]
After updating to the recent 0.43.x version I see issues with power, power_0, power_1 and energy, energy_0, energy_1 entities found for some of my Shelly 2.5 devices. 

For some of my Shelly 2.5 I see that they were already reporting sensor.shelly_2_5_*_power_0 and sensor.shelly_2_5_*_power_1 for a long time. They still work like this in the current release. Same for the power entity.

For some of my Shelly 2.5 I see that they were previously discovered and reported as sensor.shelly_2_5_*_power. Now they are discovering sensor.shelly_2_5_*_power_0 and sensor.shelly_2_5_*_power_1 after an update but don't report values for them. These entities are reporting an "unknown" state.

The affected devices are all configured as "Roller Shutter". In this mode the devices web interface is showing only one power measurement. It looks to me that the device should only discover and report one value for energy and one for power in this mode.

The devices are all at firmware 20211109-125214/v1.11.7-g682a0db.

I am not sure which version introduced the issue, but it may have started with 0.43.*. I downgraded to 0.42.9 and it worked as before.

**Comment by LarsMichelsen** [comment]
Just found #226. Seems to be the same issue.

Even if it will work suddenly as for the reporter of #226. I am still not sure if it should work like this. I also did not see anything about this change and the intention in the change logs.

From MQTT I see the following data:

shellies/shellyswitch25-68C63AF9D353/relay/energy = 3692
shellies/shellyswitch25-68C63AF9D353/roller/0/energy = 3692

In case these values would result in energy_0 and energy_1 this seems to be useless because that's redundant information in shutter mode.

**Comment by LarsMichelsen** [comment]
I've now attached an extract from the home-assistant.log which was created with 0.43.3.

Btw. might help users to have a) an issue template in this repo asking for the necessary details when creating an issue  and b) add some more details to https://github.com/bieniu/ha-shellies-discovery#how-to-debug for users to guide them through the log creation and extract process.

[home-assistant.log](https://github.com/bieniu/ha-shellies-discovery/files/7830731/home-assistant.log)

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/233

**Comment by LarsMichelsen** [comment]
Thank you! Works as expected since yesterday.
