### ISSUE TITLE
Exclude device from discovery

### ISSUE THREAD

**Issue by szat688** [bieniu/ha-shellies-discovery#24]
It would be useful, if I could set some devices to exclude from discovery, for example by writing 'manual' to configuration.
I need to define a shelly1 as a cover component with custom state_topic and payloads. I could set it manually if the script wouldn't find it.

**Comment by szat688** [comment]
Is there any chance to implement this feature?
I'm just enquiring about it.
Thank you!

**Comment by bieniu** [comment]
Yes, there is but it will take a while.

**Comment by szat688** [comment]
Ok, I understand.
That's enough for me.
Thanks!

**Comment by bieniu** [comment]
I found some time today so... done ;)

**Comment by szat688** [comment]
Wow, that was really quick! :D
Thank you for your work!
