### ISSUE TITLE
Shelly EM is still reporting the energy counter as measurement

### ISSUE THREAD

**Issue by gigatexel** [bieniu/ha-shellies-discovery#243]
See screenshot below, should be 'energy' instead of 'measurement'. Is valid for all Wh/kWh measurements on Shelly EM
Using latest script and latest HA version.

![image](https://user-images.githubusercontent.com/65073191/149484588-bb9c11ad-34ea-473b-b123-d949195e2b36.png)

![image](https://user-images.githubusercontent.com/65073191/149485564-b9c995cc-28fa-457e-a8b0-97d0bd7d153b.png)

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/244
