### ISSUE TITLE
Newly installed device not being found 

### ISSUE THREAD

**Issue by timknowlden** [bieniu/ha-shellies-discovery#246]
**Describe the bug**
Discovery not picking up newly installed shelly 1. Have many of these already which integrated okay. Same firmware and settings as all of these that have been integrated for 6months+
Native HA shelly integration picks up device okay. 

**Expected behavior**
Should discover same all previous shellies.

**Versions:**
 - Home Assistant: 2021.12.9
 - Shellies Discovery: 0.43.7
 - Shelly device firmware: 20211109-124958/v1.11.7-g682a0db 

**Shellies Discovery automation:**

```alias: Shellies Discovery
mode: queued
max: 999
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'

```

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
Please read the log, your automation is invalid.
