### ISSUE TITLE
ShellyEM Energy sensor shouldn't be `total_increasing`

### ISSUE THREAD

**Issue by eretna** [bieniu/ha-shellies-discovery#265]
**Describe the bug**
Home Assistant throws an alert warning saying: 
`Entity sensor.shelly_em_[serial]_energy_0 from integration mqtt has state class total_increasing, but its state is not strictly increasing. [...]`
Same warning is shown for `_energy_1` sensor.
I've checked the value graph and the values reported from that sensor are not increasing, it's a realtime measurement.

**Expected behavior**
Those sensors should be configured as state class measurement.

**Versions:**
 - Home Assistant: 2022.2.9
 - Shellies Discovery: 0.43.12
 - Shelly device firmware: 20220209-094734/v1.11.8-g8c7bb8d

**Shellies Discovery automation:**
Default one.

**Debug log:**
Not related.

**Comment by eretna** [comment]
And the same occurs for the `_returned_energy_*` sensor

**Comment by bieniu** [comment]
There is no real-time energy measurement, energy is the amount of power over time, so the value should keep increasing.

**Comment by eretna** [comment]
This is the historical graph of the sensor:
![984398E8-5FFC-471D-99BA-227843C2907C](https://user-images.githubusercontent.com/560031/156055116-ec4cb4e6-1c0c-4ae9-9465-6b49a8e0ab0d.jpeg)
As you can see, it’s not increasing.
Also, the home assistant warning is there.

**Comment by eretna** [comment]
If you want, I can provide more info to diagnose what’s happening.

**Comment by bieniu** [comment]
This is a device issue, ask support about it.

**Comment by eretna** [comment]
This is the raw data of the energy topic from the MQTT broker:

<img width="543" alt="Captura de Pantalla 2022-03-01 a les 11 36 59" src="https://user-images.githubusercontent.com/560031/156154101-5c553eab-6acb-47e6-868e-5ae1aca7fdff.png">
<img width="540" alt="Captura de Pantalla 2022-03-01 a les 11 37 14" src="https://user-images.githubusercontent.com/560031/156154109-b044167d-44c0-4da3-8c4d-9459f039946b.png">
<img width="538" alt="Captura de Pantalla 2022-03-01 a les 11 37 25" src="https://user-images.githubusercontent.com/560031/156154129-4629cd4b-37d3-4ae9-b093-5174463104c8.png">

From what I can see, it seems that the ShellyEM accumulates the data per minute and publishes it. This behaviour matches the ShellyEM API [documentation](https://shelly-api-docs.shelly.cloud/gen1/#shelly-em-overview):

`shellies/shellyem-<deviceid>/emeter/<i>/energy energy counter in Watt-minute`

and

`Note, that energy and returned_energy do not survive power cycle or reboot -- this is how the value is implemented on other Shellies. Shelly EM features a persisted version which is not affected by power cycling or lack of connectivity. To get the persisted counters use total and total_returned.`

So from Shelly side I think that's the expected behaviour.

**Comment by bieniu** [comment]
Could you show the history of the power value?

**Comment by eretna** [comment]
**From HA** (timeframe: last 3 hours)

<img width="1160" alt="energy" src="https://user-images.githubusercontent.com/560031/156256202-84e73a87-e5ef-401e-b3bb-485e18f41f33.png">
<img width="1163" alt="power" src="https://user-images.githubusercontent.com/560031/156256230-18a2ef3b-734f-4cbd-9536-ddd656de3702.png">


**From MQTT broker** (timeframe: last 15 minutes)

<img width="849" alt="mqtt broker" src="https://user-images.githubusercontent.com/560031/156256482-f524e04f-ef91-4354-8424-95f62c80028e.png">

**Comment by ilkobg** [comment]
Hi @eretna, @bieniu,

`energy` (and resp. `returned_energy`) topic does not accumulate the power. The last sent value is the consumed power for the last minute.

`total` (and `total_returned`) topic is accumulated energy counter, which is stored in nvm memory and kept until reset - as @eretna  cited the API documentation.

![image](https://user-images.githubusercontent.com/22872717/156356049-2345a054-cb5e-40b6-9715-ade454bec720.png)
