### ISSUE TITLE
Shelly DW unavailable after 14 hours 

### ISSUE THREAD

**Issue by martinpichlo** [bieniu/ha-shellies-discovery#268]
Hi,

I'm using several battery-powered Shelly Door/Windows Devices (1+2). Unfortunately my devices are switching to unavailable, after arround 14 hours without opening and closing. Unfortunately some of my windows are often not used for weeks.

My Settings within Shelly:
- MQTT with retain activated
- CoIoT deactivated (but I also tried it with active CoIoT without luck. Has this any effect, when using MQTT?)

My current customizing within the Shellies Discovery automation:
```
shelly-dw-mqttprefix:
  force_update_sensors: true
```

What I fond out:
- The 14 hour corresponds to the default value of the "expire_after" parameter (https://github.com/bieniu/ha-shellies-discovery)
- restarting HA sets the the unavailable devices back to the last known status (so retain is working fine)
- the problem occurs, because the DW's do not send any update, when the status is not changed. Regarding bug #93 the parameter "force_update_sensors: true" should solve this issue. But for me it did not (https://github.com/bieniu/ha-shellies-discovery/issues/93)

Questions:
- Did I miss anything?
- Do I have to explicitly define the devices as battery-powered?
- Is it possible to deactivate expiring for my devices?
- How could I find out, if force_update is working well?
- How often "force_update_sensors" should sent an update and how could I change these setting?
- How could I achieve, that the devices stop switches to unavailable

Kind Regards
Martin

**Comment by bieniu** [comment]
> because the DW's do not send any update, when the status is not changed
So this a problem related to devices. Shelly DW should send status every 12h.

**Comment by martinpichlo** [comment]
Hi,

I have understood that the problem is the device. But somewhere in the existing defects I found that shelly is not planning to change anything. So should I change to other hardware (what is ok for me)? Or do I have a chance to get it working?

In the above mentioned threads you mentioned the force update parameter. Could it helps here?

kind regards
Martin

**Comment by bieniu** [comment]
As far I know, DW with current firmware sends status every 12h. So your problem can be related to old firmware or network problem.

**Comment by bieniu** [comment]
What firmware version are your devices using? Show me debug log for a python script to check if the device configuration is valid.

**Comment by martinpichlo** [comment]
Before going into detail: are the shelly dw‘s working properly over mqtt in your opinion? Have you seen devices without the unavailability problem? 

and regarding your question: could you give me two hints:

1. where can I found how to configure shellys probably for your script?
2. Can you give me a hint, how to activate the debug lig for the needed case and how to log, what you need?

**Comment by bieniu** [comment]
> Before going into detail: are the shelly dw‘s working properly over mqtt in your opinion? Have you seen devices without the unavailability problem?

I don't have DW/DW2 in my network so I'm not 100% sure but almost a thousand people use this script and currently only you have problems with DW availability so... I think problem is related to your network or a device firmware.

> 1. where can I found how to configure shellys probably for your script?

Configure MQTT, that's all what you need.

> 2. Can you give me a hint, how to activate the debug lig for the needed case and how to log, what you need?

Please read the documentation, everything is there https://github.com/bieniu/ha-shellies-discovery/blob/master/README.md

**Comment by martinpichlo** [comment]
> What firmware version are your devices using?
It's 20220209-093605/v1.11.8-g8c7bb8d

> Show me the debug log for a python script to check if the device configuration is valid.
I got hundreds lines in the logger. I try to finde some meaningful. Is the needed information includes or do you need the full output?

`2022-03-06 23:38:45 INFO (SyncWorker_3) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shelly-dw-Kuechenfenster', 'mac': 'E8DB84D49CD8', 'fw_ver': '20220209-093605/v1.11.8-g8c7bb8d', 'model': 'SHDW-2', 'mode': '', 'host': '192.168.0.86', 'qos': 2, ..., 'shelly-dw-Kuechenfenster': {'force_update_sensors': True}, ...


2022-03-06 23:38:46 DEBUG (SyncWorker_3) [homeassistant.components.python_script.shellies_discovery.py] {'topic': 'homeassistant/binary_sensor/shelly-dw-Kuechenfenster-opening/config', 'payload': '{"name": "Shelly Door/Window 2 Kuechenfenster Opening", "stat_t": "~sensor/state", "en": "true", "uniq_id": "shelly-dw-kuechenfenster-opening", "qos": 2, "dev": {"cns": [["mac", "e8:db:84:d4:9c:d8"]], "name": "Shelly Door/Window 2 Kuechenfenster", "mdl": "Shelly Door/Window 2", "sw": "20220209-093605/v1.11.8-g8c7bb8d", "mf": "Allterco Robotics", "cu": "http://192.168.0.86/"}, "~": "shellies/shelly-dw-Kuechenfenster/", "pl_on": "open", "pl_off": "close", "exp_aft": 51839, "dev_cla": "opening", "frc_upd": "true"}', 'retain': True, 'qos': 0}`

**Comment by bieniu** [comment]
The device configuration looks good.

Could you test your device with firmware 1.11.7?

**Comment by martinpichlo** [comment]
I did a firmware downgrade to 20211109-125737/v1.11.7-g682a0db.
Let's wait for 14 hours ;-)

**Comment by martinpichlo** [comment]
The problem still exists:
I closed the window at 21:18. And it is unavailable since 11:42. 

Any idea?

**Comment by martinpichlo** [comment]
Sorry for the delay. Do you have a clue how to analyze if the device is sending an update? I could not found any timestamp.

**Comment by martinpichlo** [comment]
In my opinion it's a general device bug. As mentioned in my first post, there is the following official shelly support answer posted in #93:

> The state is sent only on change. It's inappropriate for the door state to be sent periodically with the other parameters, because it has only two states. Also, many users use automation based on the door state, so if you receive the same door state on the periodic update, it would not be correct (it means for example that the door is closed, but it was closed also before sending the periodic update). I hope you understand why this is intentionally made like that.

So I ask myself if there are Shelly Door/Window Instances running over MQTT without the unavailable bug!?

Nevertheless, I found the most messy workaround: Because the device is not sending an update any 12-14 hours, home assistant takes it over:

```
alias: Timer - Door/Window Repeat Status every 12 hours
description: ''
trigger:
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '00:00:00'
condition:
  - condition: not
    conditions:
      - condition: state
        state: unavailable
        entity_id: binary_sensor.shelly_door_window_haustuer_opening
action:
  - service: mqtt.publish
    data:
      topic: shellies/shelly-dw-Haustuer/sensor/state
      payload: >-
        {% if states.binary_sensor.shelly_door_window_haustuer_opening.state ==
        "on" %} open {% else %} close {% endif %} 
mode: single
```

Any comments?

Thanks
Martin

**Comment by jimboid** [comment]
I noticed this around January time, though I fixed it in my HA by adding back the opening check into the following code in the binary sensor part, my current version is 0.43.7 so its on line 3348, but in the latest version it looks like line 3416 would be about the right place
 
`    if battery_powered and bin_sensors[bin_sensor_id] not in [
        SENSOR_FIRMWARE_UPDATE,
        SENSOR_OPENING,
    ]:
        payload[KEY_EXPIRE_AFTER] = expire_after
    elif not battery_powered:
        payload[KEY_AVAILABILITY_TOPIC] = TOPIC_ONLINE
        payload[KEY_PAYLOAD_AVAILABLE] = VALUE_TRUE
        payload[KEY_PAYLOAD_NOT_AVAILABLE] = VALUE_FALSE
`
Been working flawlessly with my 21 DW2 contacts since adding that check back into the code.

**Comment by martinpichlo** [comment]
Hey,

thanks for the update. It seems to work for the first moment. But after some hours my devices are unavailable again. Any ideas? Do I need to have any special settings or firmware versions?

Thanks a lot.

Martin

**Comment by bieniu** [comment]
Check your log.
