### ISSUE TITLE
state-class not set

### ISSUE THREAD

**Issue by inch1957** [bieniu/ha-shellies-discovery#270]
I have several shelly 1PM devices I'd like to integrate into the energy dashboard, but (apparently) the settings ae not compatible.
Having checked the generated entries in the core.entity.registry I see that the state-class is not set to measurements. Not sure if there are other dependencies.
Please advise is I need to check/set other things.
Thanks!!!
:-)
Charles

**Comment by bieniu** [comment]
Please fill up the issue template.

**Comment by inch1957** [comment]
Happy to do so, sorry I am new to this, where do I find the template?

**Comment by bieniu** [comment]
https://github.com/bieniu/ha-shellies-discovery/issues/new?assignees=&labels=bug&template=bug_report.md&title=
