### ISSUE TITLE
Shelly-TRV-Bedroom-3 being renamed to Shelly Valve 3

### ISSUE THREAD

**Issue by wranglatang** [bieniu/ha-shellies-discovery#288]
Hello, I have just brought 9 new TRV's and I have been going through and setting them up.
When i got to doing the bedrooms i noticed that the devices where being renamed between MQTT and Home Assistant. It seems that firstly "TRV" is being changed to just "Valve" but then also words relating to rooms (specially bedrooms) are also being changed.

Here is a list of what I'm seeing:
| Name in Shelly GUI | Name in Home Assistant |
| --- | --- |
| Shelly-TRV-Bedroom-2 | Shelly Valve 2 |
| Shelly-TRV-Bedroom-3 | Shelly Valve 3 |
| Shelly-TRV-Master-Bedroom | Shelly Valve Bedroom |

Also, here is a screenshot of whats being published to MQTT & what ends up in home assistant:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/30660751/165955188-ab16e5a3-7660-4433-9df9-787bfe0f33b7.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/30660751/165955236-3b8b3a18-c299-45c7-9ea5-7ca945ea6e6b.png">

**Comment by bieniu** [comment]
The script uses the last part of `device_id` as the identifier to generate the device name and this can't be changed due to Shelly default `device_id` format. You can use [`device_name`](https://github.com/bieniu/ha-shellies-discovery#device-arguments) argument.
