### ISSUE TITLE
Use the new update entities

### ISSUE THREAD

**Issue by RouNNdeL** [bieniu/ha-shellies-discovery#290]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Home Assistant 2022.4 introduced update entities. Replacing the current `binary_sensor` and the `button` to update the firmware would be a great improvement. 

**Additional context**

https://www.home-assistant.io/blog/2022/04/06/release-20224/#introducing-update-entities
https://www.home-assistant.io/integrations/update/

**Comment by bieniu** [comment]
HA MQTT integration doesn't support update platform so currently this feature request is not possible to implement.
