### ISSUE TITLE
Shelly EM Total consumption report

### ISSUE THREAD

**Issue by jonferreira** [bieniu/ha-shellies-discovery#296]
Hi.

I just took some time to update to the latest version which went well except that, apparently, power consumption is now being reported in Wh instead of kWh.

This means that, for example, my Shelly EM Total Consumption skyrocket since it's now 1000x

![image](https://user-images.githubusercontent.com/7714292/171911921-c681e0ea-6bd2-4f98-9828-0b1f0323f97d.png)

Certainly this can't be right?

HA expects a kWh figure since that's pretty much the standard and now I have all the statistics inherent broken.

**Versions:**
 - Home Assistant: 2022.6
 - Shellies Discovery: latest
 - Shelly device firmware: latest

**Comment by jonferreira** [comment]
OK so I just found out that a new use_kwh option was introduced and default to false which to me seems pretty odd and a great way to break things.

that said, it's sorted, my fault for not doing due diligence, thanks

**Comment by bieniu** [comment]
So what is the problem?

**Comment by pannal** [comment]
Seems like this can be closed as non-issue.
