### ISSUE TITLE
Rgbw2 Switch

### ISSUE THREAD

**Issue by dodg3r** [bieniu/ha-shellies-discovery#30]
Hi and thanks for all your great work with shellies discovery :)

I´m using the switch input om my rgbw2 as an integration for my alarm-system.
When my alarm is "on", my switch turns to "on" on my rgbw2. And when my alarm is "off" the switch turns "off".
I have the button detached in my shelly configuration and my question is if there is any chance of getting it to show up in hassio with your script ?

Thanks.

/Jerry

**Comment by bieniu** [comment]
Please, show me `input` topic for RGBW2 (with value). There is no information about that on Shelly Docs page.

**Comment by dodg3r** [comment]
Hi, quick reply :) thanks.
I´m not sure if it is this you mean ?

"mode":"white","input":0,"lights"

**Comment by bieniu** [comment]
No, you have to use [MQTT Explorer](http://mqtt-explorer.com) or mosquitto_sub for that.

**Comment by bieniu** [comment]
You have to look for something like this:
```
shellies/shellyrgbw2-<ID>/input/0 0
shellies/shellyrgbw2-<ID>/input/0 1
```

**Comment by dodg3r** [comment]
Yes, think i found it.

When its "OFF"
input
0 = 0

When its "ON"
input
0 = 1

**Comment by bieniu** [comment]
Please show me the whole topic not only its values.

**Comment by dodg3r** [comment]
Sorry for not understanding.
Is this what you need ? 

shellies/shellyrgbw2-6EA0F4/input/0

![rgbw2_input](https://user-images.githubusercontent.com/46417555/76409959-743f4c80-638f-11ea-8a0c-50901dc8a9b1.PNG)

**Comment by bieniu** [comment]
Yes, this is it. Thanks. I will try to add this feature tonight.

**Comment by dodg3r** [comment]
That would be really nice.

Thank you, thank you, thank you :)

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/commit/059fae8349c03b631c8d0ec22702624088dc7d79

**Comment by dodg3r** [comment]
Hi.
Thanks for the quick update but there is something wrong. The sensor doesnt switch from off to on

2020-03-11 17:06:05 WARNING (MainThread) [homeassistant.components.mqtt.binary_sensor] No matching payload found for entity: Shelly RGBW2 6EA0F4 Input 0 with state topic: shellies/shellyrgbw2-6EA0F4/input/0. Payload: , with value template Template("")

**Comment by bieniu** [comment]
Should be fixed via https://github.com/bieniu/ha-shellies-discovery/commit/5f10fd4c6a9c8d388901ebb0e1e93a661414ef14

**Comment by dodg3r** [comment]
Hi, it´s mee again :)

The sensor gets unavailable a few seconds after I press announce.

Can you see something wrong in the log file ?
I pressed the announce script at 08:36 in the log file.
[RGBW.txt](https://github.com/bieniu/ha-shellies-discovery/files/4322903/RGBW.txt)

**Comment by bieniu** [comment]
Only this one entity gets `unvailable` state? Other RGBW2 entities are `available` all the time?

**Comment by dodg3r** [comment]
Hi. 
I have two rgbw2 units and both of them gets unavailable

**Comment by bieniu** [comment]
Unavailable state means that device is not reachable, disconnected from the MQTT broker. Maybe WiFi issue?

**Comment by dodg3r** [comment]
The rgbw2 unit is very close to the ap so there is no signal issue.
Its strange that only the rgbw2 is affected.
When I look in mqtt explorer the topic value changes but its says unavailable in hassio.
Look att this video when I press announce.

https://1drv.ms/v/s!AgZRSIF72Mnv7GuX7fjugGhIxkxe

**Comment by dodg3r** [comment]
Restarted my mqtt server and now it works. Strange.

Thanks..

**Comment by bieniu** [comment]
Your video clip made me aware of something. Binary sensor input has the same unique_id for RGBW working in both color and white modes. The script first removes the sensor for color mode, and then creates it again for white mode or vice versa. Stupid me. Thanks. I will fix that today.

**Comment by bieniu** [comment]
Fix: https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.17.5

**Comment by dodg3r** [comment]
Yes. Its working. Thanks a lot 😀
