### ISSUE TITLE
Problem with Shelly Temperature Addon

### ISSUE THREAD

**Issue by cthiele-mogic** [bieniu/ha-shellies-discovery#301]
I added the temperature addon to my already installed&configured Shelly 1PM in HA, on the device everything is working fine, I see all my temperatures - but in HA the new entities are missing?  How do I "refresh" the entities?  The temperature addon should be integrated since 2020.

**Comment by bieniu** [comment]
Did you update the script configuration? https://github.com/bieniu/ha-shellies-discovery#device-arguments

**Comment by cthiele-mogic** [comment]
I am not so familiar with that, how to use this? I have to use it on console / script ?

**Comment by cthiele-mogic** [comment]
I cannot test at the moment because the device Shelly1PM is shown unavailable, but the internal shelly webserver works fine on the given ip address.  I'll try to really remove the device. I have 10 other Shelly 2.5, they work like a charm without any problem.

**Comment by cthiele-mogic** [comment]
Works after removing the device completely and reinstall it....thank you!

**Comment by bieniu** [comment]
Please close the issue if it is resolved.

**Comment by cthiele-mogic** [comment]
Thanks
