### ISSUE TITLE
Shelly Plug US

### ISSUE THREAD

**Issue by sgstokes** [bieniu/ha-shellies-discovery#309]
I recently acquired a Shelly Plug US.  After running `http://192.168.1.31/rpc/Shelly.GetDeviceInfo` I see a get the following: `"model":"SNPL-00116US","gen":2`.  In the shellies_discovery.py I see the following:

`MODEL_SHELLYPLUG_US_ID = "SHPLG-U1"  # Shelly Plug US`.

Please correct the file to address the new model and/or direct me to another solution.

Thank you,
Stephen

**Comment by bieniu** [comment]
This is Shelly Plus Plug US and this is a gen2 device, so you have to use a gen2 script https://github.com/bieniu/ha-shellies-discovery-gen2
