### ISSUE TITLE
Device Automation Trigger "First button" pressed not working

### ISSUE THREAD

**Issue by dylan09** [bieniu/ha-shellies-discovery#327]
After updating to version 1.0.0 I have to update a lot of node-red flows where I am using "input" and "longpush" sensors.
I am using this sensors in several flows. 

I have tried to get it working using the HA companion device node. Trigger "First button" pressed is never fired for my Shelly 1. "First button" released worked as expected.
Tried also with an automation inside HA. Also "First button" pressed trigger is never fired.

I expect to get the trigger "First button" pressed to be fired, wenn the Shell input is set to on.

**Versions:**
 - Home Assistant: 2022.10.5
 - Shellies Discovery: 1.0.0
 - Shelly device firmware: 1.11.8

Sidenote:  
In Node-Red the usage of the "old" sensors was easier than the new device automation triggers. With the old sensor I need one node to get a state change for the Shelly.
With the trigger I need one node for the press trigger and another for the release trigger.

Maybe we could get back the old sensors?

**Comment by bieniu** [comment]
You have to disable option "Don't activate if the button is long pushed".
![image](https://user-images.githubusercontent.com/478555/197416980-42c5e77e-26f2-4863-b733-1cdc5cc6e35f.png)
