### ISSUE TITLE
Enable device entities in the Discovery script configuration

### ISSUE THREAD

**Issue by gogbg** [bieniu/ha-shellies-discovery#337]
**Is your feature request related to a problem? Please describe.**

Add the ability specify which device entities should be enabled or disabled in the discovery script configuration.
E.g, Enable the device IP sensor in the discovery script configuration:
![image](https://user-images.githubusercontent.com/18483384/201512265-187c64c4-2da9-4490-947a-aeb5b755eb14.png)

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/18483384/201512316-e342ff12-2a8a-47fc-9774-bc5d885e6f12.png)

**Additional context**

**Comment by bieniu** [comment]
What is the difference between enabling an entity in the UI and adding this option to the YAML configuration? Please explain the benefits of this feature. I don’t see any.

**Comment by gogbg** [comment]
1. When you have large number of devices it's a tremendous amount of clicking to configure all of their entities. E.g. I have ~50 shelly devices and I've spent around a day to configure all of them, now I have to do it again because of.... reasons...
2. When you have to reinstall/migrate the home assistant it's easier to have everything in the configuration
3. YAML code can be stored in git repositories which leads to tons of other opportunities

**Comment by bieniu** [comment]
To implement this well, for each entity it should be possible to override the default enable value, which will cause a lot of complication in the script code. The script is written in Restricted Python, so sometimes simple things take a lot of work. From my point of view, there is no advantage to complicate the code.

Let's leave this FR open, maybe someone will be interested in its implementation, I will not work on such a feature.

**Comment by danriedl** [comment]
**Somehow Offtopic**
@gogbg, something I experienced aswell. In general a lot of integrations (not this one, i love it), strive to be configured only through the user interface.
That's not necessarily a bad thing, but if you're operating a mass of devices (like you), it can get time-consuming pretty quickly.
Also, this is a huge disadvantage if you are a friend of GitOps and automated infrastructure. 👍

**Comment by LordShadowen** [comment]
Giving my 👍 to this feature as well. 

When managing large amounts of Shelly devices, being able to specify it on the script is not only much faster, it's **repeatable**.  I've had to remove and re-add many devices to HA (for various reasons), and having to re-enable disabled entities through the UI every time is kind of a PITA.

Also, and I say this with complete respect. the decision of what should be disabled or enabled by default seems arbitrary, and probably based on the opinion of  the "usefulness" of each entity by @bieniu  :)
I too find the IP address to be extremely important, and always have to enable it manually, just like @gogbg 

One alternative suggestion then: if being able to specify this per entity is too complicated, what about just defining at global level what should be enabled/disabled by default?
I've done this as a quick hack by changing  `KEY_ENABLED_BY_DEFAULT: True` on any sensor that I considered important, and this applies to all my Shelly devices. But obviously I dislike locally changing code like this... it would be much nicer to have it in the YAML
