### ISSUE TITLE
Support Bulbs RGBW as home assistant light

### ISSUE THREAD

**Issue by Geertvdc** [bieniu/ha-shellies-discovery#354]
the Shelly RGBW bulbs are not fully supported at the moment.
I have 2 bulbs and they are discovered via mqtt but you only get 4 properties
- IP address
- rssi
- ssid
- uptime

To make it useful there should also be a light object to control the actual light which is now not possible.

Is it possible to add this?

**Comment by bieniu** [comment]
Shelly RGBW bulbs are not supported https://github.com/bieniu/ha-shellies-discovery/pull/325
