### ISSUE TITLE
Any Interest In "Outside of Home Assistant" Deployment Options?

### ISSUE THREAD

**Issue by jlrgraham** [bieniu/ha-shellies-discovery#364]
I've been maintaining a forked copy of this repository that builds a Docker image that contains the discovery process form this repository and then a small Python wrapper script that fakes the interaction with the Home Assistant MQTT publish events -- instead just taking care of the publish directly to MQTT.

My personal use case is to decouple the Shelly discovery process from Home Assistant itself.  I'm running this container in a local Kubernetes cluster alongside Home Assistant.

Would there be any interest in adding this as a deployment option for the official repository?

* [Docker Image README](https://github.com/jlrgraham/ha-shellies-discovery/blob/master/DOCKER.md)
* The [wrapper script](https://github.com/jlrgraham/ha-shellies-discovery/blob/master/run.py) that runs in the container and emulates the Home Assistant service for MQTT publish events.
* [Docker Hub Images](https://hub.docker.com/repository/docker/jlrgraham/ha-shellies-discovery/general)

---

I've also got similar builds for the Shelly Gen 2 repo.

**Comment by bieniu** [comment]
Hi

It's quite an interesting idea to run the script from a separate container. Of course PR is welcome.
