### ISSUE TITLE
Devices naming similar to Native Shelly Addon

### ISSUE THREAD

**Issue by maslyankov** [bieniu/ha-shellies-discovery#398]
**Is your feature request related to a problem? Please describe.**

I want to make the python script and automation to create devices and entities similar to how the native Home Assistant Shelly integration does things. Meaning that, when you have put the time and effort to properly name the device and relays I do not see any reason to have to rename the devices and entities in Home Assistant again, furthermore name such as "Shelly 1 767F29" tells you *nothing* about where this device is and etc.

**Describe the solution you'd like**

Have the devices be named as they have been configured in their web config.

**Additional context**

Example name of Shelly gen2 device with no changes in Home Assistant: "KitchenLights" - same as in the device web config.

Thanks!

**Comment by bieniu** [comment]
This cannot be implemented due to Shelly firmware limitations. The script uses the `announce` payload to configure the device and this payload doesn't contain the device name. You can use the script configuration to pass the device name to the script.
