### ISSUE TITLE
HACS direct link and search does not work

### ISSUE THREAD

**Issue by welo78** [bieniu/ha-shellies-discovery#4]
Hi I just wanted to let you know that it is not possible to search for your component in HACS in HA. 

Neither it is possible through the link you provided. However manual installation is still possible I guess.

![image](https://user-images.githubusercontent.com/42773655/66654400-68155e80-ec3a-11e9-87b4-703a8d539f46.png)

**Comment by bieniu** [comment]
I just checked and Shellies Discovery is in HACS as usual.

**Comment by bieniu** [comment]
I chcecked few times and links are correct and script installation from HACS works.

**Comment by tofuSCHNITZEL** [comment]
Asd of now Shellies Discovery is not listed in HACS plugins or integrations

**Comment by bieniu** [comment]
Yes, you're right because Shellies Discovery isn't plugin nor integration, it's python script.

**Comment by tofuSCHNITZEL** [comment]
okay so "You can install this script via HACS" is not possible ;)

**Comment by bieniu** [comment]
Are you sure?
![shell](https://user-images.githubusercontent.com/478555/71077957-b9852100-2188-11ea-86e8-d1dcd28fdb58.png)

**Comment by tofuSCHNITZEL** [comment]
oh sorry. I had the legacy yaml config active and the python scripts were not enabled.
