### ISSUE TITLE
Feature request: add long- and shortpush sensors again please

### ISSUE THREAD

**Issue by maltesen** [bieniu/ha-shellies-discovery#416]
Hey bieniu!

Thank you very much for your script in the first place!

Some time back in my old version of the script you also added short and longpush sensors for i.e. the shelly 1 and shelly 2.5. now recenttly i updated you script and added some new shellies but those sensors are not created anymore. I do use those though. I.e. i use shortpush to turn on a light on a timer and longpush to turn it on permanently. What i could do now is modify your script to create those sensors or use the old script, but i would like to be able to update the script AND have those sensors. Forking your code just creates a mess in the longrun.

Would you be so kind to add the long and shortpush sensors again? maybe you can initially hide such probably not often used features in HA, but imo all the functionality should in principle be available - thats kinda the purpose of this script, imo.

I atttached my old version (hat to rename the ending to .txt to be able to attach it here) here below where you can search for "longpush" to see how it was done back then.

Thank you very much!
[shellies_discovery_Modified_by_Malte.txt](https://github.com/bieniu/ha-shellies-discovery/files/11358938/shellies_discovery_Modified_by_Malte.txt)

**Comment by bieniu** [comment]
You can use device automation triggers https://github.com/bieniu/ha-shellies-discovery#how-to-use-device-automation-triggers

If you need special operations on events, the `input` entity is available.

**Comment by maltesen** [comment]
im not sure if i get you correclty here. you suggest, that i implement the short and longpush in software by using timings between events via automation triggers in home assistant?

im working on a VERY lossy wifi connection. the shellies in question are far out in the garden. i do not get any accurate timing reliably from those. im happy if i get a message at all and already wrote quite some workarounds (ACKs) for writing the other direction from HA to the shellies) already. if your suggesting that, thats a toi unstable solution.

**Comment by maltesen** [comment]
or are you suggesting to automate adding the short and longpush sensors in a 2nd script? which imo kinda is the main purpose of your script in the first place.

**Comment by bieniu** [comment]
> im not sure if i get you correclty here. you suggest, that i implement the short and longpush in software by using timings between events via automation triggers in home assistant?

No, long and short push events are available via device automation triggers. Just use them in your automations.

**Comment by maltesen** [comment]
thanks. ill check those out
