### ISSUE TITLE
Support for SHCB-1 (Shelly Bulb RGBW GU10)

### ISSUE THREAD

**Issue by tc-maxx** [bieniu/ha-shellies-discovery#424]
**Is your feature request related to a problem? Please describe.**

   The "Shelly Bulb RGBW GU10" is not recognized by the script.

**Describe the solution you'd like**

   Please add support for model: SHCB-1

**Additional context**

{
    "id": "Gaden_01_Blub",
    "model": "SHCB-1",
    "mac": "349454xxxxxx",
    "ip": "192.168.1.16",
    "new_fw": false,
    "fw_ver": "**20230503**-095009/v1.13.0-g9aed950"
}

**Comment by bieniu** [comment]
MQTT configuration for SHCB is not fully compatible with HA MQTT integration. At least I didn't manage to create a properly working configuration.

**Comment by bieniu** [comment]
I'll check that.

**Comment by tc-maxx** [comment]
The payload for the MQTT Discovery looks like this:
```
{
 "unique_id": "Garten_01_Bulb_oben",
 "name": "Garten_01_Bulb_oben",
 "state_topic": "shellies/Garten_01_Blub_oben/color/0/status",
 "command_topic": "shellies/Garten_01_Bulb_oben/color/0/set",
 "command_on_template": "{ \"turn\":\"on\", {%if red is defined and green is defined and blue is defined%} \"mode\":\"color\", \"red\":{{red}}, \"green\":{{green}}, \"blue\":{{blue}}, {%endif%} {%if brightness is defined%} \"gain\":{{brightness | float | multiply(0.3922) | round(0)}}, \"brightness\":{{brightness | float | multiply(0.3922) | round(0)}}, {%endif%} {%if effect is defined%} {%if effect==\"Meteor Shower\"%} \"effect\":1 {%elif effect==\"Gradual Change\"%} \"effect\":2 {%elif effect==\"Breath\"%} \"effect\":3 {%elif effect==\"Flash\"%} \"effect\":4 {%elif effect==\"On/Off Gradual\"%} \"effect\":5 {%elif effect==\"Red/Green Change\"%} \"effect\":6 {%else%} \"effect\":0 {%endif%} {%else%} \"effect\":0 {%endif%} {% if color_temp is defined %} \"mode\":\"white\", \"temp\":{{(1/(color_temp | float)) | multiply(1000000) | round(0)}}, {% endif %} }",
 "effect_list": [
 "Off",
 "Meteor Shower",
 "Gradual Change",
 "Breath",
 "Flash",
 "On/Off Gradual",
 "Red/Green Change"
 ],
 "command_off_template": "{\"effect\":0,\"turn\":\"off\"}",
 "state_template": "{% if value_json.ison %}on{% else %}off{% endif %}",
 "brightness_template": "{{value_json.brightness | float | multiply(2.55) | round(0)}}",
 "color_temp_template": "{{1000000 | multiply(1/(value_json.temp | float)) | round(0)}}",
 "red_template": "{{[value_json.red](http://value_json.red/)}}",
 "green_template": "{{[value_json.green](http://value_json.green/)}}",
 "blue_template": "{{[value_json.blue](http://value_json.blue/)}}",
 "effect_template": "{{value_json.effect}}",
 "qos": 2,
 "retain": true,
 "max_mireds": 333,
 "min_mireds": 154,
 "device": {
    "connections": [
      [
        "mac",
        "34:94:54:6e:83:0a"
      ]
    ],
    "name": "Shelly Bulb RGBW Garten_01_Bulb_unten",
    "model": "Shelly Bulb RGBW",
    "sw_version": "20230503-095009/v1.13.0-g9aed950",
    "hw_version": "gen1 (SHCB-1)",
    "manufacturer": "Allterco Robotics",
    "configuration_url": "http://192.168.1.26/"
  } 
}
```

**Comment by bieniu** [comment]
I tested your configuration a few days ago and it works but unfortunately I don't have time to implement it in the script. Maybe at the weekend...

**Comment by bieniu** [comment]
I see a big problem with your configuration. If you set a color for the light and then switch back to white mode, the light icon still shows the last used color. So far I have no idea how to get around this.

**Comment by tc-maxx** [comment]
Have you ever used this somewhere, I'd like to take a look?

**Comment by bieniu** [comment]
No, I haven't used such calculations anywhere, I suspect that we will find something like that in the MQTT integration code.

**Comment by Xinayder** [comment]
I was messing around with this, trying to implement it by myself and found out that the `template` schema doesn't support color modes: https://www.home-assistant.io/integrations/light.mqtt/#comparison-of-light-mqtt-schemas

So, I used the work from the OP and finally implemented a light that works with my Shelly Duo RGBW GU10. The trick was to pass `none` to `red_template` fields, so Lovelace can correctly display the white temperature of the lamp if it's not using RGB.
