### ISSUE TITLE
Shelly Door/Window 2 always show up as unavaliable after a restart of home assistant

### ISSUE THREAD

**Issue by shreyasajj** [bieniu/ha-shellies-discovery#438]
**Is your feature request related to a problem? Please describe.**
Home assistant annouces to discover every device in mqtt; however, since shelly door/window sensor goes to sleep till triggered, the door shows up as unavaliable till someone opens the door.

**Describe the solution you'd like**
Can we make it so that Home assistant will pull from the lattest log from mqtt on that sensor and use that value

**Additional context**

**Comment by bieniu** [comment]
It's not possible to implement in the script. The state will be restored at HA start if the device sends the state with retain flag.
