### ISSUE TITLE
Info: "mqtt":disabled?

### ISSUE THREAD

**Issue by quenthal** [bieniu/ha-shellies-discovery#441]
I've around 40-50 Shelly devices. After updating the script to the latest and also Home Assistant itself, two devices have been unavailable. 

I noticed that info payload mqtt was disabled:
{"wifi_sta":{"connected":true,"ssid":"IoT_keittio","ip":"192.168.50.102","rssi":-76},"cloud":{"enabled":false,"connected":false},_"**mqtt":{"connected":false}**_,"time":"20:00","unixtime":1688662801,"serial":1,"has_update":false,"mac":"98F4ABD0A900","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"lights":[{"ison":true,"source":"mqtt","has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"mode":"white","brightness":100,"transition":0}],"meters":[{"power":29.16,"overpower":0.00,"is_valid":true, "timestamp":1688673601,"counters":[29.221, 29.198, 29.212],"total":807}],"inputs":[{"input":0,"event":"","event_cnt":0},{"input":0,"event":"","event_cnt":0}],"tmp":{"tC":47.31,"tF":117.16, "is_valid":true},"calib_progress":0,"overtemperature":false,"loaderror":0,"overpower":false,"update":{"status":"idle","has_update":false,"new_version":"20230510-082818/v1.13.1-gda6f9f2","old_version":"20230510-082818/v1.13.1-gda6f9f2"},"ram_total":50264,"ram_free":38228,"fs_size":233681,"fs_free":128763,"uptime":1956}

I manually send the same info, but replaced disabled with enabled. It works for some time, until "info" is for some reason updated.

How to fix this permanently? Why something is sending mqtt: disabled to my mqtt broker?

**Comment by bieniu** [comment]
It seems that the device is sending information that MQTT is disconnected. So the script and entity configuration is working fine.

**Comment by BadCo-NZ** [comment]
I also have this problem only on my two dimmer2s after updating firmware to 1.13.1.

If I delete the `info` topic in mqtt explorer, then run the `Shelly Announce` script, the `info` topic comes back with `"mqtt":{"connected":false}` still there.

Manually publishing with `"mqtt":{"connected":true}` enables it.

I have tried disabling/enabling mqtt in the Shelly webUI, but that didn't change anything.

Next step is to try a factory reset.

**Comment by bieniu** [comment]
If the device sends `"mqtt":{"connected": false}’ even though it is connected, you should ask Shelly support about this problem.

**Comment by BadCo-NZ** [comment]
This is definitely a bug in 1.13.1 firmware, this issue can be closed.

For internet searchers though, here is my process for figuring this out.

* changing MQTT settings in the Shelly webGUI then disabling/enabling MQTT didn't fix the bug
* factory reset didn't fix the bug
* rolling back to 1.11.8 didn't fix the bug
* resetting MQTT settings in the Shelly webGUI after rolling back finally changed `"mqtt":{"connected": false}` to `"mqtt":{"connected": true}`
