### ISSUE TITLE
SystemError: AST constructor recursion depth mismatch (before=33, after=60)

### ISSUE THREAD

**Issue by jsapede** [bieniu/ha-shellies-discovery#448]
**Describe the bug**
Error message in Hass system logs :

Shellies Discovery: Error executing script. Unexpected error for call_service at pos 1: AST constructor recursion depth mismatch (before=33, after=60)

appears each time shellies discovery is executed 

**Versions:**
 - Home Assistant: 
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Interface utilisateur : 20230705.1 - latest 

 - Shellies Discovery: 4.3

 - Shelly device firmware: 
Current version: 20230503-095514/v1.13.0-g9aed950
You have latest version on your device!

**Shellies Discovery automation:**

- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.gen is not defined }}'
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model | default }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'

**Comment by bieniu** [comment]
Please attach debug log https://github.com/bieniu/ha-shellies-discovery#how-to-debug
Only English is allowed in the issue description. Please edit the content.

**Comment by jsapede** [comment]
content edited but the french part was from the HA Logs
debucg log launched

**Comment by jsapede** [comment]
this ?

Logger: homeassistant.components.automation.shellies_discovery
Source: components/python_script/__init__.py:153
Integration: Automatisation (documentation, issues)
First occurred: 15:00:00 (2 occurrences)
Last logged: 15:00:00

Shellies Discovery: Error executing script. Unexpected error for call_service at pos 1: AST constructor recursion depth mismatch (before=33, after=61)
While executing automation automation.shellies_discovery
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2013, in _execute_service
    return await self._hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 112, in python_script_service_handler
    execute_script(hass, call.service, call.data)
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 146, in execute_script
    execute(hass, filename, source, data)
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 153, in execute
    compiled = compile_restricted_exec(source, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RestrictedPython/compile.py", line 87, in compile_restricted_exec
    return _compile_restricted_mode(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RestrictedPython/compile.py", line 52, in _compile_restricted_mode
    c_ast = ast.parse(source, filename, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: AST constructor recursion depth mismatch (before=33, after=61)

**Comment by bieniu** [comment]
This is not a log file.

**Comment by jsapede** [comment]
> This is not a log file.

where to find the log ? 

here the screenshot

![Screenshot_2](https://github.com/bieniu/ha-shellies-discovery/assets/66303110/8d697a69-4d8a-4a6c-af11-3f5c50ea8bb5)

**Comment by bieniu** [comment]
I think this is not related to the script. Look here https://github.com/home-assistant/core/issues/95364

**Comment by majdzik84** [comment]
Same here

**Comment by bieniu** [comment]
This is not related to the script.
