### ISSUE TITLE
discovering shelly devices

### ISSUE THREAD

**Issue by hros** [bieniu/ha-shellies-discovery#468]
Hi,
I came across your [blog with the templates for MQTT Shelly integration with HA](https://sequr.be/blog/2020/10/mqtt-templates-for-shelly-devices)
Based on your template, I created an entry for a Shelly i3 device and restarted HA, but I do not see this device.

Before I install your automated device discovery tool, I want to be able to find my device and understand the various entries in the template.

When I test the MQTT integration by publishing a "shellies/command; announce" I get several messages from the device. This indicates that the communication configuration is OK.

I entered the template for the i3 (with the device id, and a chosen name), but after restarting HA, I get the following error message in HA:
```
Unused YAML configuration for the mqtt integration

It's not possible to configure mqtt sensor by adding platform: mqtt to the sensor configuration. Please check the documentation for more information on how to set up this integration.

To resolve this:

Remove platform: mqtt occurences from the sensor: configuration in your YAML configuration file.
Restart Home Assistant.
Example that should be removed:

sensor:
  - platform: mqtt
```

btw, your template has the field: `expire_after: 604800`, is that necessary?
does it mean that if the device was silent for a week it should be removed?

**Comment by bieniu** [comment]
> Please check the documentation for more information on how to set up this integration.

Your configuration is deprecated, read the documentation to avoid this message.


> btw, your template has the field: `expire_after: 604800`, is that necessary?
> does it mean that if the device was silent for a week it should be removed?

You can find information about MQTT options in the documentation: https://www.home-assistant.io/integrations/binary_sensor.mqtt/#expire_after

**Comment by hros** [comment]
thanks, @bieniu 
after `ignore`-ing the error it did not reappear. I guess it was not an issue with a "deprecated configuration", but the error was raised during one of my initial setups, and I did not clear it
Anyway, the configuration does not complain, but I still can't find my mqtt device/entity in HA for the Shelly i3 I setup.
I followed your [binary sensor template for i3](https://sequr.be/blog/2020/10/mqtt-templates-for-shelly-devices/#binary-sensors-1) and tried adding it either under `switch:` or under `sensor:` but did not see the new device in the devices/entities list

Note that the device is discovered with the Shelly integration with the CoIoT protocol, but I want to switch to MQTT

I did not find anything useful in the docs. What step am I missing to access the device in HA?

**Comment by bieniu** [comment]
> after `ignore`-ing the error it did not reappear. I guess it was not an issue with a "deprecated configuration"

If your config looks like this
```yaml
sensor:
  - platform: mqtt
```
it is deprecated.

> I did not find anything useful in the docs. What step am I missing to access the device in HA?

I don't know 🤷‍♂️ I won't guess what your configuration looks like. If you have a problem with the Shellies Discovery script, please open a ticket and describe it. If you need help setting up MQTT... sorry, but this isn't the place to do it.
