### ISSUE TITLE
shelly 1 with 3 temp sensors addon

### ISSUE THREAD

**Issue by Roger-NL1975** [bieniu/ha-shellies-discovery#47]
I have a shelly 1 with 3 temp sensors working fine, and sending MQTT payloads:
shellies/shelly1-F42054/ext_temperature_f/0
shellies/shelly1-F42054/ext_temperature_f/1
shellies/shelly1-F42054/ext_temperature_f/2
shellies/shelly1-F42054/ext_temperature/0
shellies/shelly1-F42054/ext_temperature/1
shellies/shelly1-F42054/ext_temperature/2
(monitored with MQTT.fx)
but in HA Mosquito MQTT intergrations it only shows up with relais and input as if no addon attached,
is this correct and do I need to setup sensors throu yaml?

or am I doing someting wrong.

**Comment by bieniu** [comment]
The script doesn't know that your Shelly has sensors connected. Please read the documentation.

**Comment by Roger-NL1975** [comment]
Thx now I get how the costume config works, just didn't get it the first time and because al was fine, I didn't bother to really get in to it, but now I see what it's doing I get it.

**Comment by bieniu** [comment]
```
shelly1-F42054:
        ext-0: "temperature"
        ext-1: "temperature"
        ext-2: "temperature"
```
