### ISSUE TITLE
Invalid event type error in logs

### ISSUE THREAD

**Issue by zylxpl** [bieniu/ha-shellies-discovery#474]
Some errors spoted int the logs
Logger: homeassistant.components.mqtt.event
Source: components/mqtt/event.py:190
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 17:38:21 (1 occurrences)
Last logged: 17:38:21
Invalid event type for event.shelly_1_salus_button_0 received on topic shellies/shelly1-8CAAB548291D-salus/input_event/0, payload {"event_type":""}

Device is sending periodical updates with empty event_type field which is nor correctly handled.

**Comment by bieniu** [comment]
Please fill up the issue template.
