### ISSUE TITLE
All Shellies unavailable with 0.22 and latest home assistant.

### ISSUE THREAD

**Issue by vekexasia** [bieniu/ha-shellies-discovery#52]
Hello, it looks like that 0.22 with latest home assistant 0.111.* do not work.

I can see the messages going back and forth in MQTT but all devices are offline.

**Comment by bieniu** [comment]
I use HA 0.111 and script 0.22 and everything are working as usual.

**Comment by prndlrm** [comment]
Sometime while updating to 0.22 and 0.111.1 all my shelly devices and entity IDs got renamed from things like **Shelly-LaundryArea** back to **Shelly 1 C4F7B9**, breaking all automations. I restarted and ran Shellies Announce and anything else I could think of but only manually renaming them fixed it. Glad I only have a handful of Shelly devices.

**Comment by bieniu** [comment]
@prndlrm It's possible if you update from version older than 0.19.

**Comment by domeq** [comment]
It's actually a different rename, my device IDs changed from `shelly1_...` to `shelly_1_...` and `shelly2_...` to `shelly_2_...` effectively breaking all automations.

Search & replace of my configs fixed it.

**Comment by bieniu** [comment]
@domeq Yes, you're right. I forgot about that. My mistake.

**Comment by bieniu** [comment]
No further information, closing.
