### ISSUE TITLE
Shelly UNI "ext_" parameters implementation to sensor HA block (entity)

### ISSUE THREAD

**Issue by ltksolutions** [bieniu/ha-shellies-discovery#523]
Hi,
first of all, congratulations and thank you, great work these scripts ... 👌

but,
I miss the implementation of external temperature and humidity sensors with Shelly UNI, more in the pictures below

On the link https://shelly-api-docs.shelly.cloud/gen1/#shelly1-1pm-mqtt is implementation "ext" sensors for Shelly1/1PM, but these sensors use Shelly UNI and Shelly Plus Uni too.

Thanks for all support from you, ATB.

Shelly1/1PM also provide aggregated topics which contain data from all sensors along with their hardware IDs. They publish a JSON payload similar to the one in [/status](https://shelly-api-docs.shelly.cloud/gen1/#shelly1-1pm-status)

shellies/model-deviceid/ext_temperatures
{
    "0":{"hwID":"XXXXXXXX","tC":20.5},
    "1":{"hwID":"YYYYYYYY","tC":21.5},
    "2":{"hwID":"ZZZZZZZZ","tC":22.5}
}
shellies/model-deviceid/ext_temperatures_f
{
    "0":{"hwID":"XXXXXXXX","tF":68.9},
    "1":{"hwID":"YYYYYYYY","tF":70.7},
    "2":{"hwID":"ZZZZZZZZ","tF":72.5}
}
shellies/model-deviceid/ext_humidities
{
    "0":{"hwID":"XXXXXXXX","hum":50}
}

<img width="1221" alt="MQTT-explorer-shelly-uni" src="https://github.com/bieniu/ha-shellies-discovery/assets/8642569/0e4ea588-d224-4db1-84c6-d31d44f82995">

<img width="1585" alt="HA-MQTT-Shelly-UNI-ext_devices-needed" src="https://github.com/bieniu/ha-shellies-discovery/assets/8642569/30f77dcc-9ab9-4ffd-93ab-e5db14216937">

**Comment by bieniu** [comment]
Did you read the documentation of the script?

![image](https://github.com/bieniu/ha-shellies-discovery/assets/478555/91da3f4d-6138-4ac9-811c-21d1ba055350)

**Comment by ltksolutions** [comment]
let me be forgiven :) thank you ...
