### ISSUE TITLE
Shelly 2.5 Roller state

### ISSUE THREAD

**Issue by plumped** [bieniu/ha-shellies-discovery#58]
Hi Bieniu

Thank you for your hard work on this plugin, its really helpfull.
I'm really new with MQTT and i was wondering where i can find the actual state of my 2.5. I use them as Shutters in Roller mode. DO I have to change something in your configs to get there?

At the moment i'm using the "cover.shelly_shsw_25_xxxxxxxx" service, but this state is no instant and takes always 10 seconds to switch to the correct state.

Thanks for your help!

**Comment by bieniu** [comment]
> DO I have to change something in your configs to get there?

You have to add `mode: "roller"` for this device.

**Comment by plumped** [comment]
Wow that was quick response :-) where exactly do i have to add it?

**Comment by bieniu** [comment]
You have an example in the documentation https://github.com/bieniu/ha-shellies-discovery#custom-configuration-example

**Comment by plumped** [comment]
It works now, great!

Is there an option to get open/close/stop command on a single button each? Like the "cover.open_cover" for exemple?
I want to use it with single buttons with own icons if its possible

Thank you in advance

**Comment by bieniu** [comment]
https://www.home-assistant.io/integrations/cover/#services

**Comment by plumped** [comment]
I'm a fucking idiot xD thanks a lot and have a great day!

**Comment by bieniu** [comment]
There are no stupid questions 😉 I wish you a great day too.
