### ISSUE TITLE
Shelly Door/Window 2

### ISSUE THREAD

**Issue by Jaguaza** [bieniu/ha-shellies-discovery#59]
My shelly door windows 2 is not recognized. Could you give support, please.

**Comment by bieniu** [comment]
Could you share MQTT topics/payloads, please 😉

**Comment by Jaguaza** [comment]
Hello I hope to help with this.

Close:
![close](https://user-images.githubusercontent.com/46264854/88451071-34679600-ce54-11ea-902b-f473110f10ef.png)
Topic:  shellies/shellydw2-A4CF12F43189/sensor/state

Open:
![open](https://user-images.githubusercontent.com/46264854/88451089-55c88200-ce54-11ea-8b02-cf8d414b558b.png)
Topic: shellies/shellydw2-A4CF12F43189/sensor/state

Tilt open:
![tilt open](https://user-images.githubusercontent.com/46264854/88451121-890b1100-ce54-11ea-8c90-48e4c5539af0.png)
Topic: shellies/shellydw2-A4CF12F43189/sensor/tilt

Vibration on:
![vibration on](https://user-images.githubusercontent.com/46264854/88451143-a6d87600-ce54-11ea-903c-74a223daf86a.png)
Topic: shellies/shellydw2-A4CF12F43189/sensor/vibration

Topic temperature: shellies/shellydw2-A4CF12F43189/sensor/temperature

Topic lux: shellies/shellydw2-A4CF12F43189/sensor/lux

Topic ilumination: shellies/shellydw2-A4CF12F43189/sensor/illumination

Topic battery: shellies/shellydw2-A4CF12F43189/sensor/battery

Topic error: shellies/shellydw2-A4CF12F43189/sensor/battery

Topic act_reasons: shellies/shellydw2-A4CF12F43189/sensor/act_reasons

Topic online: shellies/shellydw2-A4CF12F43189/online

**Comment by bieniu** [comment]
Is the `error` sensor a binary sensor (values `0` and `1`)?
Does the `act_reason` sensor has always value `["sensor"]`?

**Comment by Jaguaza** [comment]
> ¿Es el `error`sensor un sensor binario (valores `0`y `1`)?
> ¿El `act_reason`sensor siempre tiene valor `["sensor"]`?


That's how it appears to me, I don't know what it's for.

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.26.0
