### ISSUE TITLE
Add ability to ignore temperature changes in Shelly2.5

### ISSUE THREAD

**Issue by playmobil42** [bieniu/ha-shellies-discovery#61]
Looking at the event stream in Developer tools I see many small internal temperature change events coming from my shelly 2.5's internal sensors. My understanding is that this sensor is for internal overheating protection so it's state is not so useful in Home Assistant for most people.

Suggest adding ability to ignore these events and as they are just noise, e.g :

{
    "event_type": "state_changed",
    "data": {
        "entity_id": "sensor.shelly2_5_111111_temperature",
        "old_state": {
            "entity_id": "sensor.shelly2_5_111111_temperature",
            "state": "58.5",
            "attributes": {
                "unit_of_measurement": "°C",
                "friendly_name": "Shelly 2.5 111111 Temperature",
                "device_class": "temperature"
            },
            "last_changed": "2020-07-25T06:57:40.851376+00:00",
            "last_updated": "2020-07-25T06:57:40.851376+00:00",
            "context": {
                "id": "b3b092c652b345f2a3bda6a7ca4a7ffd",
                "parent_id": null,
                "user_id": null
            }
        },
        "new_state": {
            "entity_id": "sensor.shelly2_5_111111_temperature",
            "state": "58.4",
            "attributes": {
                "unit_of_measurement": "°C",
                "friendly_name": "Shelly 2.5 111111 Temperature",
                "device_class": "temperature"
            },
            "last_changed": "2020-07-25T06:59:10.706531+00:00",
            "last_updated": "2020-07-25T06:59:10.706531+00:00",
            "context": {
                "id": "99de225021244b30ab9fd4eaab5c8d9c",
                "parent_id": null,
                "user_id": null
            }
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-07-25T06:59:10.706575+00:00",
    "context": {
        "id": "99de225021244b30ab9fd4eaab5c8d9c",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by bieniu** [comment]
It's not possible via discovery script. You should as Shelly Support for help with this issue.

**Comment by playmobil42** [comment]
Thank you, the request is for the discovery script to add a configuration option to not add the overheat sensor for the Shelly 2.5 to begin with - this would remove the noise from this sensor.

Would you be willing to accept a patch for such an option?

**Comment by bieniu** [comment]
The script isn't a good place to manage entities. That's what the Entity Registry in Home Assistant is for. You can disable this entity there.
