### ISSUE TITLE
Reconnection problems

### ISSUE THREAD

**Issue by Jaguaza** [bieniu/ha-shellies-discovery#63]
Good.
Can you help me, before I had declared everything manually and had no problem.

Now with the integration when I restart home assistant or when I restart the home wifi, the shellys are disconnected and I can only reconnect if I enter the shelly web ui and in mqtt options without changing anything to save.

https://www.youtube.com/watch?v=GbXJBNRnpBw
https://www.youtube.com/watch?v=0Fd1QgCsCzU

**Comment by bieniu** [comment]
Sorry, I can't help. This may be a network or MQTT issue. Try to read MQTT broker log.
