### ISSUE TITLE
Breaking change (id->dev_id) introduced in 0.27.1

### ISSUE THREAD

**Issue by mikeage** [bieniu/ha-shellies-discovery#68]
The changelog for 0.27.1 just mentions "small fixes", but this version changed the parameter to the python script from id to dev_id, so the automation needs to be updated as well:

```patch
@@ -16,7 +18,7 @@
   action:
   - service: python_script.shellies_discovery
     data_template:
-      id: '{{ trigger.payload_json.id }}'
+      dev_id: '{{ trigger.payload_json.id }}'
       mac: '{{ trigger.payload_json.mac }}'
       fw_ver: '{{ trigger.payload_json.fw_ver }}'
```

I'm not opening a PR because I'm not sure if you want to revert this and release it as part of a new major version (0.28) or something.

**Comment by bieniu** [comment]
Stupid mistake, thanks!
Fixed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.27.2
