### ISSUE TITLE
Light Dimmer doesn't turn on 

### ISSUE THREAD

**Issue by denniswham** [bieniu/ha-shellies-discovery#71]
I have 5 dimmers. 4 of them work okay, the fifth does report the state perfectly fine, but I cannot turn on/off the light in HA. In the web interface of the dimmer all goes well. I have tried removing the entity, and having it re-provisioned. I see it appearing in the Mosquitto add-on log (and it should otherwise it can't report the state).
Anything else that I'm missing?

**Comment by bieniu** [comment]
Use version 0.27.2 of the script, version 0.27.3 has an issue for lights.

**Comment by denniswham** [comment]
Thanks for the prompt response, and good to know! I don't see an option in HACS to select a version of a module. Can you give me a direction please?

**Comment by bieniu** [comment]
If you click "Reinstall", you will be able to select the version to install.

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.27.4

**Comment by denniswham** [comment]
Thank you sir!
