### ISSUE TITLE
uptime in seconds rather than days

### ISSUE THREAD

**Issue by mikeage** [bieniu/ha-shellies-discovery#72]
Currently, the uptime is reported in days (https://github.com/bieniu/ha-shellies-discovery/blob/master/python_scripts/shellies_discovery.py#L254 ). The raw value is seconds, and this seems to be the convention for most other devices I have. Can you report seconds directly, and if someone wants days, they can create an HA template sensor to convert it.

**Comment by bieniu** [comment]
For me more readable are days.

**Comment by bieniu** [comment]
The best solution is sensor with DateTime object as state but there is a problem with achieving this via MQTT discovery.

**Comment by mikeage** [comment]
DateTime would definitely be best, agreed.

I understand that days are more readable, but we can't convert days back to seconds without losing significant precision. Would it be possible to consider seconds and you'd do the formatting either in Lovelace or via another sensor (or perhaps via attributes)?

**Comment by bieniu** [comment]
Temporarily, I can add raw value in seconds as sensor attribute.

**Comment by mikeage** [comment]
That would work for me, thank you

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.27.6

**Comment by mikeage** [comment]
thanks!
