### ISSUE TITLE
cant auto discover shellly vintage bulb

### ISSUE THREAD

**Issue by volzb** [bieniu/ha-shellies-discovery#83]
Hi, 

I have may shelly devices connected and working but I'm unable to see my shelly vintage blub, I have factory reset the device many times and can control it through home assistant using mqtt with no issues. 

Does anyone know of a workaround?

![image](https://user-images.githubusercontent.com/6599352/92984141-71164c00-f4eb-11ea-83d2-be1fc0905e39.png)

**Comment by bieniu** [comment]
If you can control the device, it must have been configured before. So what's the problem?

**Comment by bieniu** [comment]
I answered too quickly. Can you control Shelly Vintage by sending topics via MQTT and the script doesn't recognize the device?

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.29.3

**Comment by volzb** [comment]
What a quick fix!

Coffie coming your way!
