### ISSUE TITLE
expire_after value None is not an integer

### ISSUE THREAD

**Issue by Kaibob2** [bieniu/ha-shellies-discovery#85]
There seems to be a problem with the latest version 0.30.2.
I get a bunch of the below errors each time the script gets executed.
I have 7 Shelly1 and one Shelly2.5. All of them not battery powered. I suppose this is
why the error appears.
Beside of that, thanks for the great work. I love the script as it has much more
options than the integration or the custom component. Great work!

```
Logger: homeassistant.components.python_script.shellies_discovery.py
Source: components/python_script/__init__.py:205
Integration: Python Scripts (documentation, issues)
First occurred: 16:00:00 (40 occurrences)
Last logged: 20:00:02
Error executing script: expire_after value None is not an integer

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1757, in <module>
TypeError: expire_after value None is not an integer

```

**Comment by bieniu** [comment]
What a stupid mistake. Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.30.3
