### ISSUE TITLE
Add support for Shelly Plug G2/Europe(?) Version

### ISSUE THREAD

**Issue by alexsrb** [bieniu/ha-shellies-discovery#88]
Hi,

The Plug version that I have just received - Model: Shelly PLUG (S171) - is not discovered/added by the script.
The Plus is updated to the latest firmware version available: 20200827-070415/v1.8.3@4a8bc427.

Using MQTT Explorer, the related announce messages contains "model": "SHPLG2-1"
![image](https://user-images.githubusercontent.com/4201994/95649450-1d951f00-0ae6-11eb-99c4-ee515996c837.png)
In the discovery script there is no entry for this model
![image](https://user-images.githubusercontent.com/4201994/95649501-57662580-0ae6-11eb-963c-20ec29a58675.png)

If I change MODEL_SHELLYPLUG_ID from "SHPLG-1" to "SHPLG2-1", the Plug appears under devices, together with the associated entities.

What additional information/actions would you need from my side in order to analyse and solve this issue?
Thank you in advance for your support!

**Comment by bieniu** [comment]
Please show me the `announce` topic that the device sends when connected to power.

**Comment by alexsrb** [comment]
![image](https://user-images.githubusercontent.com/4201994/95653063-62c54b00-0afe-11eb-8f32-9517d73c3e97.png)

**Comment by alexsrb** [comment]
![image](https://user-images.githubusercontent.com/4201994/95653077-7375c100-0afe-11eb-8ec1-4e30b3ba928f.png)

**Comment by bieniu** [comment]
I need `id`. You can hide the part with MAC.

**Comment by alexsrb** [comment]
"id": "shellyplug-s-9A3124"

**Comment by alexsrb** [comment]
![image](https://user-images.githubusercontent.com/4201994/95657036-f278f280-0b1a-11eb-8683-2eb0008f2672.png)

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/89

**Comment by alexsrb** [comment]
I confirm that it works. Thanks for the quick fix!
