### ISSUE TITLE
Question regarding Shelly 2.5 Current State when in Roller mode

### ISSUE THREAD

**Issue by thesorin** [bieniu/ha-shellies-discovery#90]
### Question: Is the shelly 2.5 configured as Roller missing the current device state: STOP | OPEN | CLOSE ? Or it's missing implmenetation?

As per MQTT documentation from shelly [MQTT in Roller mode](https://shelly-api-docs.shelly.cloud/#mqtt-in-roller-mode) the device reports on topic `shellies/shellyswitch25-<deviceid>/roller/0` states `open`, `close` when in motion or `stop` when not moving.

I don't see any sensor or a cover attribute that could expose this property. Am I missing something or is it missing from implementation?

### Current Configuration:
> shellyswitch25-######:
>....mode: roller
>....roller-0-name: Covers Office
>....roller-0-class: shutter

Edit:
the cover.covers_office properly report state "open" pos < 100 or "closed" when pos = 100; and that is fine. I am actually looking for current state of the cover.

I am attempting to use a zig bee button that will:
- stop the covers if state is "open" or "close"
- open the cover if previous state was "close"
- close the cover if previous state was "open"

**Comment by bieniu** [comment]
`state_topic` is listening topic `shellies/shelly<model>-<deviceid>/roller/0` https://github.com/bieniu/ha-shellies-discovery/blob/master/python_scripts/shellies_discovery.py#L1534
So all the states the device sends are available in the Home Assistant.

You can look here https://github.com/bieniu/ha-shellies-discovery/issues/84

**Comment by thesorin** [comment]
Ok, so I think I know why the state outputs only "open" and  "closed" for roller. 

It's because, correct me if I am wrong, but it's basically because we track the roller position topic ( https://github.com/bieniu/ha-shellies-discovery/blob/307305a994deb3188900b9a43f7c3488b27a8a1c/python_scripts/shellies_discovery.py#L1536 ), this makes state_topic ignored because position_topic is present and in and the documentation from Home Assistant Cover Mqtt Integration states that this fact: https://www.home-assistant.io/integrations/cover.mqtt/#state_topic.

For now, I have created myself some mqtt sensors following that topic there. Would be nice to have the sensor "roller action" present under the same device for ease of access.

Thanks for taking the time.

**Comment by bieniu** [comment]
You're right, I missed this. Thanks.

**Comment by bieniu** [comment]
Please test this version https://github.com/bieniu/ha-shellies-discovery/blob/master/python_scripts/shellies_discovery.py
You have to replace `shellies_discovery.py` file in `/config/python_scripts`.

With this change the `cover` entity should `roller state` attribute.

**Comment by thesorin** [comment]
Looks fine:

![image](https://user-images.githubusercontent.com/12372349/98119482-54780e00-1eb5-11eb-8a3d-20a9573ed9a7.png)

I appreciate

**Comment by bieniu** [comment]
Great, thanks for help with testing

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.32.1

**Comment by bieniu** [comment]
@thesorin Thanks for your donation!

**Comment by thesorin** [comment]
thank you!
