### ISSUE TITLE
Shelly i3 repeating binary sensor

### ISSUE THREAD

**Issue by davidw3591** [bieniu/ha-shellies-discovery#91]
Hi,

I'm testing a Shelly i3 in HomeAssistant with the discovery script. Latest Shelly firmware and version 0.117.1 of homeAssistant.

All input combinations (single, double, triple, long, ...) are detected perfectly, but the last input detection repeats every time the Shelly sends an update message. The Shelly sends the update message every 30 seconds.

For example:
* I perform a triple push on input 0
*** Received MQTT message: shellies/shellyix3-10521CF2C2C2/input_event/0 --> {"event":"SSS","event_cnt":4}
*** Result: binary_sensor.shelly_i3_10521cf2c2c2_triple_shortpush_0 turns on for a second
* Now every 30 seconds this binary sensor turns on for a second
*** Receives the same input_event every 30s: {"event":"SSS","event_cnt":4}
*** Also when I publish the same message on the same topic above with MQTT.fx, HomeAssistant enables the triple_shortpush_0 binary sensor

When I test a longpush on one of my Shelly 1's, detection is not repeated after initial detection.
The Shelly 1 publishes the same message every 30 seconds:
*** shellies/shelly1-10521C454394/input_event/0 --> {"event":"L","event_cnt":849}
*** This does not retrigger the binary sensor

**Comment by bieniu** [comment]
It's firmware issue. I can't do anything with that. You can change update period to 0 then device will not send repeated events.

**Comment by davidw3591** [comment]
I'm having trouble to understand why this issue does not exist with for example the Shelly 1? It also sends a similar event message every 30 seconds and there is no repeated event in HomeAssistant?

**Comment by bieniu** [comment]
Script uses for Shelly 1 topic `shellies/<model>-<deviceid>/longpush/0` to generate `longpush` and `shortpush` entities. Shelly i3 doesn't send such topic.

**Comment by davidw3591** [comment]
> Script uses for Shelly 1 topic `shellies/<model>-<deviceid>/longpush/0` to generate `longpush` and `shortpush` entities. Shelly i3 doesn't send such topic.

That makes sense, thanks for explaining.
