### ISSUE TITLE
Add value_template for position topic and set_position_template

### ISSUE THREAD

**Issue by Bascht74** [bieniu/ha-shellies-discovery#96]
Hello there.

Good work with that script!

**Is your feature request related to a problem? Please describe.**
E.g. in Germany there are roller shutters that do not move to the centre via position "50". This is because they have "slits" and move down even further when the window is optically almost darkened.

Example video where you can see this: 
https://www.youtube.com/watch?v=PCudaPpwoAM&ab_channel=TheRealSamWalton
(1:20 min)

This means that you have to correct the position, e.g. 50% optically open corresponds to a position of "65".

**Describe the solution you'd like**
It would be great if you could optionally specify a `position_template` (value_template directly under position_topic, you use that yourself with `TPL_POSITION`). As well a `set_position_template`. 

e.g. The configuration for a cover could look like this 

```
      shellyswitch25-68C63AF926FB:
        mode: "roller"
        roller-0-name: "Rollo.OG.bedroom"
        roller-0-class: "shutter"
        position_template: "{{'<some code>'}}"                  <- new optional entry
        set position_template: "{{'<some code>'}}"               <- new optional entry
```
The position_template will then overwrite/replace your existing value_template for covers (`TPL_POSITION = "{%if value!=-1%}{{value}}{%endif%}"`) and the set_position_template will be added to the mqtt cover device configuration.

In this way, the position information in the output and input can be manipulated/changed as desired.

Greetings

Sebastian Lotz

**Comment by bieniu** [comment]
Give ma an example of templates that you want to use with those parameters?

**Comment by Bascht74** [comment]
```
position_template: >-
        {% if state_attr('cover.shelly_shsw_25_xxxxxxx', 'current_position') | float == 20 %}
           {{ 0 }}
        {% elif state_attr('cover.shelly_shsw_25_xxxxxxx', 'current_position') | float < 20 %}
           {{ 1 }}
        {% else %}
           {{ (1.265 * (state_attr('cover.shelly_shsw_25_xxxxxxx', 'current_position'))-26) | round(0) | int }}
        {% endif %}
      tilt_template: >-
        {% if state_attr('cover.shellyswitch25_xxxxxxx', 'current_position') | float <= 21 %}
           {{ 100 - (state_attr('cover.shellyswitch25_xxxxxxx', 'current_position') | float / 21 * 100)|int  }}
        {% else %}
           {{ 0 }}
        {% endif %}

```

**Comment by bieniu** [comment]
Thanks, I have to check if such a template can passed as `python_script` argument.

**Comment by Bascht74** [comment]
Thank you!

I could write it that way:

`position_template: '{%if value is none %}{{ null }}{%elif value | float < 0 %}{{ null }}{%elif value | float > 64 %}{{ (value | float / (100-65)*(100-50) - 65/(100-65)*(100-50) + 50) | int }}{%elif value | float > 15 %}{{ (value | float / (64-16)*(49-5) - 16/(64-16)*(49-5) + 5) | int }}{%elif value | float > 5 %}{{ (value | float / (15-6)*(4-1) - 6/(15-6)*(4-1) + 1) | int }}{% else %}{{ 0 }}{% endif %}'`

so it would be a string to pass over...

**Comment by bieniu** [comment]
Sorry, the template cannot be passed to the script. I always get the error:
```
Traceback (most recent call last):
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/homeassistant/components/automation/__init__.py", line 404, in async_trigger
    await self.action_script.async_run(
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 432, in _async_call_service_step
    domain, service, service_data = async_prepare_call_from_config(
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 190, in async_prepare_call_from_config
    raise HomeAssistantError(f"Error rendering data template: {ex}") from ex
homeassistant.exceptions.HomeAssistantError: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'
```

**Comment by Bascht74** [comment]
Can the template be added as a string (same way, that you use yourself in the script)?

position_template: '{%if value is none %}{{ null }}{%elif value | float < 0 %}{{ null }}{%elif value | float > 64 %}{{ (value | float / (100-65)*(100-50) - 65/(100-65)*(100-50) + 50) | int }}{%elif value | float > 15 %}{{ (value | float / (64-16)*(49-5) - 16/(64-16)*(49-5) + 5) | int }}{%elif value | float > 5 %}{{ (value | float / (15-6)*(4-1) - 6/(15-6)*(4-1) + 1) | int }}{% else %}{{ 0 }}{% endif %}'

**Comment by bieniu** [comment]
The template can be added as a const in the script, I can't find a way to pass the template from HA to the script.

**Comment by Bascht74** [comment]
can you try: 

`position_template: {{'{%if value is none %}{{ null }}{%elif value | float < 0 %}{{ null }}{%elif value | float > 64 %}{{ (value | float / (100-65)*(100-50) - 65/(100-65)*(100-50) + 50) | int }}{%elif value | float > 15 %}{{ (value | float / (64-16)*(49-5) - 16/(64-16)*(49-5) + 5) | int }}{%elif value | float > 5 %}{{ (value | float / (15-6)*(4-1) - 6/(15-6)*(4-1) + 1) | int }}{% else %}{{ 0 }}{% endif %}'}}`

and

`set_position_template: {{'{%if position | float >= 50 %}{{ (position | float / (100-50)*(100-65) - 50/(100-50)*(100-65) + 65) | int }}{%elif position | float >= 5 %}{{ (position | float / (49-5)*(64-16) - 5/(49-5)*(64-16) + 16) | int }}{%elif position | float >= 1 %}{{ (position | float / (4-1)*(15-6) - 1/(4-1)*(15-6) + 6) | int }}{% else %}{{ 0 }}{% endif %}'}}`

That should do the trick.

**Comment by bieniu** [comment]
No template is passed to the script. The Home Assistant renders a template and I get a `position is not defined` error.

**Comment by Bascht74** [comment]
Hi Bienui, 

did you realy try with {{ before and }} after the string?
I tried that in `developer tools` -> `Template` and it shows me the template string as the result and not the result of the template self.

![image](https://user-images.githubusercontent.com/66269310/101146127-eee58180-361a-11eb-984d-145f00a1f5f9.png)

If you don't use {{ }} before/after, you get the result of the processed template.

![image](https://user-images.githubusercontent.com/66269310/101146407-3ff57580-361b-11eb-9bc5-1292026a4ae8.png)

**Comment by bieniu** [comment]
You need `"` before and after template in YAML so `"{{"{{'Test'}}"}}"` will cause an error. But if there are no strings in the template there will it should work. I'll check once again.

**Comment by Bascht74** [comment]
OK, then it should be:

`position_template: "{{'{%if value is none %}{{ null }}{%elif value | float < 0 %}{{ null }}{%elif value | float > 64 %}{{ (value | float / (100-65)*(100-50) - 65/(100-65)*(100-50) + 50) | int }}{%elif value | float > 15 %}{{ (value | float / (64-16)*(49-5) - 16/(64-16)*(49-5) + 5) | int }}{%elif value | float > 5 %}{{ (value | float / (15-6)*(4-1) - 6/(15-6)*(4-1) + 1) | int }}{% else %}{{ 0 }}{% endif %}'}}"`

**Comment by bieniu** [comment]
Yup

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.34.0

**Comment by bieniu** [comment]
Thanks for help.

**Comment by Bascht74** [comment]
Thank you!
I allready sent you "a beer" the past days!

**Comment by bieniu** [comment]
Thanks, cheers 🍻
