### ISSUE TITLE
Support setting name for all entities per device

### ISSUE THREAD

**Issue by zeridon** [bieniu/ha-shellies-discovery#97]
**Is your feature request related to a problem? Please describe.**
While playing today i saw there is an option to set relay-[num] name in the automation. Of course i used it and of course it works but behaves strangely. Some entities are named as expected and some not.

I've applied this to a shelly1PM and only the relay-0 related entities are affected. All the rest (current usage, totals, etc) are still named by the device_id.

See the attached screenshot for a sample

**Describe the solution you'd like**
I would like a way to set the names for all the entities per device. I am aware that is achievable via device settings (custom mqtt prefix) but i would prefer to set it in the automation. Use case is someone has already installed the devices and configured the mqtt settings, but also has secured the web IF so it is not possible to access it and change the prefix.

**Additional context**

![shelly1pm-mixed-names](https://user-images.githubusercontent.com/5081863/100884582-533cff80-34ba-11eb-8c36-a1df75db379e.png)

**Comment by bieniu** [comment]
Changing the device name would duplicate the HA functionality.

![image](https://user-images.githubusercontent.com/478555/100885504-030e6f00-34b3-11eb-9882-3b276c00f019.png)

**Comment by zeridon** [comment]
Then why it exists for relays (it also duplicates it)?

**Comment by bieniu** [comment]
If you change the name of a relay, then the names of the sensors of the relay (power, energy) will also be changed. There is no such functionality in HA.

**Comment by Bascht74** [comment]
Thanks for pointig me to this entry, I oversaw ist. 

> If you change the name of a relay, then the names of the sensors of the relay (power, energy) will also be changed. There is no such functionality in HA.

I don't think he nor me wants to change the device name. 
We just want to "start" with new devices that way and keep the names, if a devices fails...
You are right, this is nothing for somebody who allready added a lot of devices and did a lot of stuff with the system. 
But for somebody who starts with it, it would be a nice feature to keep all entities with friendly names and have a possibilty easily exchange a shelly (what happened to me once so far).
The device ID should/could be added to the common device information, where you have e.g. the firmware stored.

Sebastian

**Comment by bieniu** [comment]
If you change the device name in HA, all entities names for that device will also change. So where is the problem?

**Comment by zeridon** [comment]
> If you change the device name in HA, all entities names for that device will also change. So where is the problem?

I did not know that :) This more or less solves my percieved issue and does make it unnecessary.

**Comment by Bascht74** [comment]
Me neither. Thx!
