### ISSUE TITLE
add IP address and mac address to the device info (connections)

### ISSUE THREAD

**Issue by Bascht74** [bieniu/ha-shellies-discovery#98]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to access the shelly devices via the web interface. You need the IP address of the device for it. 
Right now it is available in the mqtt messages `info` and `announce` but not stored in the device.

**Describe the solution you'd like**
could you add `'cns':  'connections',` to your script an add the `mac address` and `ip address` of the device.
So it will display at the device infos.

the `mac address` and `ip address` is available in the announce topic:
shellies/shellyxyz-xxxxxxxxxxxx/announce

see:
https://developers.home-assistant.io/docs/device_registry_index/#device-properties
https://www.home-assistant.io/integrations/cover.mqtt/#connections
https://www.home-assistant.io/docs/mqtt/discovery/

**Additional context**

**Comment by r3ndszergazda** [comment]
YES please!

**Comment by bieniu** [comment]
The device information screen cannot display the IP or MAC address.
https://github.com/home-assistant/frontend/blob/dev/src/panels/config/devices/device-detail/ha-device-info-card.ts#L32-L79

**Comment by Bascht74** [comment]
You were right. Thanks anyway!
